Repository anoma/juvix, pull requests merged in 2021-07, with the labels that each got.

#856 Explicit exports and removing of unused functions in IR/Evaluator.hs
  ChangeLog.org
  doc/Code/Library.org
  library/Core/src/Juvix/Core/IR/Evaluator.hs
  library/Core/src/Juvix/Core/IR/Evaluator/PatSubst.hs
  library/Core/src/Juvix/Core/IR/Evaluator/Subst.hs
  library/Core/src/Juvix/Core/IR/Evaluator/SubstV.hs
  library/Core/src/Juvix/Core/IR/Evaluator/Types.hs
  library/Core/src/Juvix/Core/IR/Evaluator/Weak.hs
Labels: enhancement

#866 Refactor pipeline
  doc/Code/Library.org
  doc/core/Pipeline.pdf
  doc/core/Pipeline.tex
  library/Backends/Plonk/test/Test/Compiler.hs
  library/Backends/Plonk/test/Test/Golden.hs
  library/Core/src/Juvix/Core/Base/Types/Base.hs
  library/Core/src/Juvix/Core/Erased/Algorithm.hs
  library/Core/src/Juvix/Core/Erased/Algorithm/Types.hs
  library/Core/src/Juvix/Core/Erased/Ann/Conversion.hs
  library/Core/src/Juvix/Core/IR/Evaluator.hs
  library/Core/src/Juvix/Core/IR/Evaluator/SubstV.hs
  library/Core/src/Juvix/Core/IR/Evaluator/Types.hs
  library/Core/src/Juvix/Core/IR/Typechecker/Error.hs
  library/Core/src/Juvix/Core/IR/Types.hs
  library/Core/src/Juvix/Core/Parameterisations/Naturals.hs
  library/Core/src/Juvix/Core/Translate.hs
  library/Core/test/Typechecker.hs
  library/EasyPipeline/src/Easy.hs
  library/EasyPipeline/stack.yaml.lock
  library/EasyPipeline/test/FromFrontend.hs
  library/Frontend/src/Juvix/Frontend.hs
  library/Pipeline/src/Juvix/Pipeline.hs
  library/Pipeline/src/Juvix/Pipeline/Compile.hs
  library/Pipeline/src/Juvix/Pipeline/Core.hs
  library/Pipeline/src/Juvix/Pipeline/Frontend.hs
  library/Pipeline/src/Juvix/Pipeline/Internal.hs
  library/Pipeline/test/Test/RecGroups.hs
  library/StandardLibrary/src/Juvix/Library/Test/Golden.hs
  library/Translate/src/Juvix/ToCore/FromFrontend/Transform/Def.hs
  library/Translate/src/Juvix/ToCore/FromFrontend/Transform/HR.hs
  library/Translate/src/Juvix/ToCore/FromFrontend/Transform/Helpers.hs
  library/Translate/src/Juvix/ToCore/FromFrontend/Transform/IR.hs
  library/Translate/src/Juvix/ToCore/FromFrontend/Transform/Sig.hs
  library/Translate/src/Juvix/ToCore/FromFrontend/Transform/TypeSig.hs
  library/Translate/src/Juvix/ToCore/FromFrontend/Transform/Usage.hs
  library/Translate/src/Juvix/ToCore/Types.hs
  library/Translate/src/Juvix/ToCore/Types/Defs.hs
  library/Translate/src/Juvix/ToCore/Types/Env.hs
  library/Translate/src/Juvix/ToCore/Types/Error.hs
  library/Translate/test/Test/Golden.hs
  test/examples-golden/positive/circuit/Datatypes/Datatypes.hr
  test/examples-golden/positive/circuit/Polynomial/Polynomial.hr
  test/examples-golden/positive/circuit/main/MainConst/MainConst.hr
  test/examples-golden/positive/circuit/main/MainMultiArgs/MainMultiArgs.hr
  test/examples/to-fix/circuit/.keep
Labels: refactoring

#840 Commenting Core's IR/Evaluator
  doc/Code/Library.org
  library/Core/src/Juvix/Core/IR/Evaluator.hs
  library/Core/src/Juvix/Core/IR/Evaluator/PatSubst.hs
  library/Core/src/Juvix/Core/IR/Evaluator/SubstV.hs
  library/Core/src/Juvix/Core/IR/Evaluator/Types.hs
  library/Core/src/Juvix/Core/IR/Evaluator/Weak.hs
Labels: documentation
