Repository anoma/juvix, pull requests merged in 2021-08, with the labels that each got.

#909 Easy pipeline erasure
  ChangeLog.org
  doc/Code/Library.org
  library/EasyPipeline/src/Easy.hs
  library/EasyPipeline/test/FromFrontend.hs
Labels: enhancement

#940 More tests for variations on datatype declarations
  test/examples-golden/positive/circuit/Datatypes/Datatypes.0-desugar-module
  test/examples-golden/positive/circuit/Datatypes/Datatypes.1-desugar-let
  test/examples-golden/positive/circuit/Datatypes/Datatypes.2-desugar-cond
  test/examples-golden/positive/circuit/Datatypes/Datatypes.3-desugar-if
  test/examples-golden/positive/circuit/Datatypes/Datatypes.4-desugar-multiple-let
  test/examples-golden/positive/circuit/Datatypes/Datatypes.5-desugar-multiple-defun
  test/examples-golden/positive/circuit/Datatypes/Datatypes.6-desugar-multiple-sig
  test/examples-golden/positive/circuit/Datatypes/Datatypes.7-desugar-remove-punned-records
  test/examples-golden/positive/circuit/Datatypes/Datatypes.8-desugar-handler-transform
  test/examples-golden/positive/circuit/Datatypes/Datatypes.A-contextify-sexp
  test/examples-golden/positive/circuit/Datatypes/Datatypes.B-resolve-module
  test/examples-golden/positive/circuit/Datatypes/Datatypes.C-resolve-infix
  test/examples-golden/positive/circuit/Datatypes/Datatypes.circuit
  test/examples-golden/positive/circuit/Datatypes/Datatypes.erased
  test/examples-golden/positive/circuit/Datatypes/Datatypes.hr
  test/examples-golden/positive/circuit/Datatypes/Datatypes.ir
  test/examples-golden/positive/circuit/Datatypes/Datatypes.parsed
  test/examples-golden/positive/circuit/Datatypes/Datatypes.typecheck
  test/examples/positive/circuit/Datatypes.ju
  test/examples/to-fix/circuit/ConflictingConstructorName.ju
  test/examples/to-fix/circuit/Datatypes.ju
  test/examples/to-fix/llvm/ConflictingConstructorName.ju
  test/examples/to-fix/llvm/Datatypes.ju
  test/examples/to-fix/michelson/ConflictingConstructorName.ju
  test/examples/to-fix/michelson/Datatypes.ju
Labels: testing, datatypes

#957 Clean ups
  ChangeLog.org
  app/Config.hs
  app/Main.hs
  app/Options.hs
  app/Version.hs
  doc/Code/App.org
  doc/Code/Library.org
  library/Backends/Michelson/src/Juvix/Backends/Michelson/Parameterisation.hs
  library/Backends/Plonk/test/Test/AnnTerm.hs
  library/Backends/Plonk/test/Test/Compiler.hs
  library/Backends/Plonk/test/Test/Example/Polynomial.hs
  library/Backends/Plonk/test/Test/Golden.hs
  library/Core/src/Juvix/Core/Base/Types/Base.hs
  library/EasyPipeline/src/Easy.hs
  library/Frontend/src/Juvix/Frontend.hs
  library/Frontend/stack.yaml.lock
  library/HTTP/src/Juvix/HTTP/API.hs
  library/HTTP/src/Juvix/HTTP/Routes.hs
  library/HTTP/src/Juvix/Orphan.hs
  library/Pipeline/src/Juvix/Pipeline.hs
  library/Sexp/stack.yaml.lock
  library/StandardLibrary/package.yaml
  library/StandardLibrary/src/Juvix/Library.hs
  library/StandardLibrary/src/Juvix/Library/BLS12381.hs
  library/StandardLibrary/src/Juvix/Library/Usage.hs
  library/StandardLibrary/stack.yaml.lock
  package.yaml
Labels: refactoring, cleanup
