Repository anoma/juvix, pull requests merged in 2022-04, with the labels that each got.

#45 [minihaskell] Do not add id suffix to top-level modules and main
  src/MiniJuvix/Translation/MicroJuvixToMiniHaskell.hs
Labels: minihaskell

#44 Output ANSI codes only if handle supports it
  app/Main.hs
  package.yaml
  src/MiniJuvix/Syntax/MiniHaskell/Pretty/Text.hs
Labels: minihaskell

#43 Short-circuit clause pattern check errors
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
  test/TypeCheck/Negative.hs
  tests/negative/MicroJuvix/WrongConstructorArity.mjuvix
Labels: type-checking

#48 Validity Predicate Example
  tests/positive/VP/Anoma.hs
  tests/positive/VP/SimpleFungibleToken.mjuvix
Labels: minihaskell

#56 Fix #29 (third attempt)
  src/MiniJuvix/Pipeline.hs
  src/MiniJuvix/Prelude/Base.hs
  src/MiniJuvix/Syntax/MicroJuvix/InfoTable.hs
  src/MiniJuvix/Syntax/MicroJuvix/MicroJuvixResult.hs
  src/MiniJuvix/Syntax/MiniHaskell/MiniHaskellResult.hs
  src/MiniJuvix/Translation/MicroJuvixToMiniHaskell.hs
Labels: enhancement

#57 Add copy of agda-input to minijuvix-mode
  minijuvix-mode/minijuvix-input.el
  minijuvix-mode/minijuvix-mode.el
Labels: enhancement

#66 Add support for compile (by Jonathan)
  src/MiniJuvix/Syntax/Abstract/InfoTable.hs
  src/MiniJuvix/Syntax/Abstract/InfoTableBuilder.hs
  src/MiniJuvix/Syntax/Abstract/Language.hs
  src/MiniJuvix/Syntax/Backends.hs
  src/MiniJuvix/Syntax/Concrete/Language.hs
  src/MiniJuvix/Syntax/Concrete/Lexer.hs
  src/MiniJuvix/Syntax/Concrete/Parser.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Error.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Error/Pretty/Base.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Error/Types.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/InfoTable.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Name/NameKind.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Base.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Scope.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Scoper.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Scoper/InfoTableBuilder.hs
  src/MiniJuvix/Syntax/MicroJuvix/InfoTable.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language.hs
  src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
  src/MiniJuvix/Syntax/MonoJuvix/InfoTable.hs
  src/MiniJuvix/Syntax/MonoJuvix/Language.hs
  src/MiniJuvix/Syntax/MonoJuvix/Pretty/Base.hs
  src/MiniJuvix/Translation/AbstractToMicroJuvix.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix.hs
  src/MiniJuvix/Translation/MonoJuvixToMiniHaskell.hs
  src/MiniJuvix/Translation/ScopedToAbstract.hs
  test/Scope/Negative.hs
  tests/negative/CompileBlocks/MultipleCompileBlockSameName.mjuvix
  tests/negative/CompileBlocks/MultipleCompileRuleSameBackend.mjuvix
  tests/negative/CompileBlocks/Sample/Definitions.mjuvix
  tests/negative/CompileBlocks/WrongKindExpressionCompileBlock.mjuvix
  tests/negative/CompileBlocks/WrongLocationCompileBlock.mjuvix
  tests/positive/Axiom.mjuvix
  tests/positive/HelloWorld.mjuvix
  tests/positive/MiniHaskell/HelloWorld.mjuvix
  tests/positive/VP/SimpleFungibleToken.mjuvix
Labels: enhancement, scoper, error-messaging

#67 check if stderr supports ANSI and print accordingly
  app/Main.hs
  package.yaml
  src/MiniJuvix/Pipeline.hs
  src/MiniJuvix/Prelude/Error.hs
  test/Base.hs
Labels: enhancement
