Repository anoma/juvix, pull requests merged in 2022-05, with the labels that each got.

#70 Monomorphization
  .hlint.yaml
  app/Commands/MicroJuvix.hs
  app/Commands/MonoJuvix.hs
  app/Main.hs
  notes/Monomorphization.org
  package.yaml
  src/MiniJuvix/Pipeline/EntryPoint.hs
  src/MiniJuvix/Prelude.hs
  src/MiniJuvix/Prelude/Base.hs
  src/MiniJuvix/Prelude/Lens.hs
  src/MiniJuvix/Prelude/Pretty.hs
  src/MiniJuvix/Syntax/Concrete/Lexer.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Scoper.hs
  src/MiniJuvix/Syntax/MicroJuvix/Error/Pretty/Base.hs
  src/MiniJuvix/Syntax/MicroJuvix/InfoTable.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language/Extra.hs
  src/MiniJuvix/Syntax/MicroJuvix/MicroJuvixTypedResult.hs
  src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
  src/MiniJuvix/Syntax/MonoJuvix/Language.hs
  src/MiniJuvix/Syntax/MonoJuvix/Language/Extra.hs
  src/MiniJuvix/Syntax/MonoJuvix/Pretty.hs
  src/MiniJuvix/Syntax/MonoJuvix/Pretty/Base.hs
  src/MiniJuvix/Syntax/MonoJuvix/Pretty/Options.hs
  src/MiniJuvix/Translation/AbstractToMicroJuvix.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix/TypeCallsMapBuilder.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix/TypePropagation.hs
  test/Main.hs
  test/MonoJuvix.hs
  test/MonoJuvix/Positive.hs
  tests/positive/Polymorphism.mjuvix
  tests/positive/VP/PolySimpleFungibleToken.mjuvix
Labels: monomorphization

#76 bump stackage version and remove allow-newer
  .github/workflows/ci.yml
  stack.yaml
Labels: operations

#71 Add terminating keyword
  app/Main.hs
  lab/Syntax/Core.hs
  src/MiniJuvix/Internal/Strings.hs
  src/MiniJuvix/Prelude/Base.hs
  src/MiniJuvix/Prelude/Pretty.hs
  src/MiniJuvix/Syntax/Abstract/InfoTable.hs
  src/MiniJuvix/Syntax/Abstract/Language.hs
  src/MiniJuvix/Syntax/Abstract/Language/Extra.hs
  src/MiniJuvix/Syntax/Abstract/Pretty/Base.hs
  src/MiniJuvix/Syntax/Concrete/Language.hs
  src/MiniJuvix/Syntax/Concrete/Lexer.hs
  src/MiniJuvix/Syntax/Concrete/Parser.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Scoper.hs
  src/MiniJuvix/Syntax/MiniHaskell/Pretty/Base.hs
  src/MiniJuvix/Syntax/MonoJuvix/Pretty/Base.hs
  src/MiniJuvix/Termination/CallGraph.hs
  src/MiniJuvix/Termination/CallMap.hs
  src/MiniJuvix/Termination/Types.hs
  src/MiniJuvix/Termination/Types/SizeRelation.hs
  src/MiniJuvix/Translation/ScopedToAbstract.hs
  src/MiniJuvix/Utils/Version.hs
  tests/negative/Termination/Loop.mjuvix
  tests/negative/Termination/ToEmpty.mjuvix
  tests/positive/Termination/TerminatingF.mjuvix
  tests/positive/Termination/TerminatingG.mjuvix
  tests/positive/Termination/ToEmpty.mjuvix
Labels: enhancement, termination

#74 Add automatically updates/issues/merged PRs to the changelog
  .github_changelog_generator
  .gitignore
  CHANGELOG.org
  Makefile
Labels: operations

#80 Remove unused constructor ExpressionTyped in Monojuvix
  src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/MiniJuvix/Syntax/MonoJuvix/Language.hs
  src/MiniJuvix/Syntax/MonoJuvix/Pretty/Base.hs
  src/MiniJuvix/Translation/MonoJuvixToMiniHaskell.hs
Labels: refactor

#68 Add C code generation backend
  .github/workflows/ci.yml
  Makefile
  README.org
  app/Commands/MiniC.hs
  app/Main.hs
  package.yaml
  src/MiniJuvix/Internal/Strings.hs
  src/MiniJuvix/Pipeline.hs
  src/MiniJuvix/Syntax/Backends.hs
  src/MiniJuvix/Syntax/Concrete/Lexer.hs
  src/MiniJuvix/Syntax/Concrete/Parser.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Base.hs
  src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/MiniJuvix/Syntax/MiniC/Language.hs
  src/MiniJuvix/Syntax/MiniC/Serialization.hs
  src/MiniJuvix/Syntax/MonoJuvix/InfoTable.hs
  src/MiniJuvix/Syntax/MonoJuvix/Language.hs
  src/MiniJuvix/Syntax/MonoJuvix/MonoJuvixResult.hs
  src/MiniJuvix/Syntax/MonoJuvix/Pretty/Base.hs
  src/MiniJuvix/Translation/MonoJuvixToMiniC.hs
  src/MiniJuvix/Translation/MonoJuvixToMiniC/Strings.hs
  src/MiniJuvix/Translation/MonoJuvixToMiniHaskell.hs
  test/BackendC.hs
  test/BackendC/Positive.hs
  test/Base.hs
  test/Main.hs
  test/Scope/Positive.hs
  tests/.gitattributes
  tests/positive/Foreign.mjuvix
  tests/positive/HelloWorld.mjuvix
  tests/positive/MiniC/HelloWorld/Input.mjuvix
  tests/positive/MiniC/HelloWorld/expected.golden
  tests/positive/MiniC/Nat/Input.mjuvix
  tests/positive/MiniC/Nat/expected.golden
  tests/positive/MiniC/Polymorphism/Input.mjuvix
  tests/positive/MiniC/Polymorphism/expected.golden
Labels: minic

#78 Stricter stack builds and pedantic mode for CI
  .github/workflows/ci.yml
  Makefile
  package.yaml
Labels: CI, operations

#91 87 refactor warning related stuff
  app/Commands/Extra.hs
  app/Commands/Html.hs
  app/Commands/MicroJuvix.hs
  app/Commands/MiniC.hs
  app/Commands/MiniHaskell.hs
  app/Commands/MonoJuvix.hs
  app/Commands/Parse.hs
  app/Commands/Scope.hs
  app/Commands/Termination.hs
  app/Main.hs
  package.yaml
  src/MiniJuvix/Internal/NameIdGen.hs
  src/MiniJuvix/Syntax/Concrete/Language.hs
  src/MiniJuvix/Syntax/Concrete/Lexer.hs
  src/MiniJuvix/Syntax/Concrete/LiteralLoc.hs
  src/MiniJuvix/Syntax/Concrete/Loc.hs
  src/MiniJuvix/Syntax/Concrete/Name.hs
  src/MiniJuvix/Syntax/Concrete/Parser.hs
  src/MiniJuvix/Syntax/Concrete/Parser/InfoTableBuilder.hs
  src/MiniJuvix/Syntax/Concrete/Parser/ParsedItem.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Error/Pretty/Base.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Name.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/NameRef.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Base.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Html.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Scope.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Scoper.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Utils.hs
  src/MiniJuvix/Syntax/Fixity.hs
  src/MiniJuvix/Syntax/MicroJuvix/InfoTable.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language/Extra.hs
  src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
  src/MiniJuvix/Syntax/MiniHaskell/Language.hs
  src/MiniJuvix/Syntax/MiniHaskell/Pretty/Base.hs
  src/MiniJuvix/Syntax/MonoJuvix/Language.hs
  src/MiniJuvix/Syntax/MonoJuvix/Pretty/Base.hs
  src/MiniJuvix/Termination/CallGraph.hs
  src/MiniJuvix/Termination/CallMap.hs
  src/MiniJuvix/Termination/Types.hs
  src/MiniJuvix/Translation/MonoJuvixToMiniC.hs
  test/Scope/Negative.hs
Labels: refactor

#96 Add usage example and move developer docs
  README.org
  docs/developer-tooling.org
Labels: documentation

#100 Support multiple modules in compilation
  src/MiniJuvix/Internal/Strings.hs
  src/MiniJuvix/Syntax/MicroJuvix/InfoTable.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language.hs
  src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
  src/MiniJuvix/Translation/AbstractToMicroJuvix.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix/TypeCallsMapBuilder.hs
  test/BackendC/Positive.hs
  tests/positive/MiniC/MultiModules/Bool.mjuvix
  tests/positive/MiniC/MultiModules/IO.mjuvix
  tests/positive/MiniC/MultiModules/Input.mjuvix
  tests/positive/MiniC/MultiModules/Pair.mjuvix
  tests/positive/MiniC/MultiModules/Prelude.mjuvix
  tests/positive/MiniC/MultiModules/String.mjuvix
  tests/positive/MiniC/MultiModules/expected.golden
Labels: enhancement

#113 Add minic-runtime for linking without libc
  README.org
  minic-runtime/libc/minic-runtime.h
  minic-runtime/standalone/minic-runtime.h
  minic-runtime/standalone/walloc.c
  package.yaml
  src/MiniJuvix/Internal/Strings.hs
  src/MiniJuvix/Translation/MonoJuvixToMiniC.hs
  src/MiniJuvix/Translation/ScopedToAbstract.hs
  test/BackendC/Positive.hs
  tests/positive/MiniC/HelloWorld/Input.mjuvix
  tests/positive/MiniC/HigherOrder/Input.mjuvix
  tests/positive/MiniC/MultiModules/IO.mjuvix
  tests/positive/MiniC/Nat/Input.mjuvix
  tests/positive/MiniC/Polymorphism/Input.mjuvix
Labels: minic

#116 Fix internal link in README
  README.org
Labels: documentation

#118 Remove dev in the CI and other tweaks
  .github/workflows/ci.yml
  .pre-commit-config.yaml
Labels: enhancement, CI

#119 Add initial docs generation website
  .github/workflows/ci.yml
  .gitignore
  Makefile
  book.toml
  docs/SUMMARY.org
  docs/developer-tooling.org
Labels: documentation, CI

#120 Add initial documentation (#119)
  .github/workflows/ci.yml
  .gitignore
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  Makefile
  README.org
  book.toml
  docs/SUMMARY.org
  docs/developer-tooling.org
  docs/org/SUMMARY.org
  docs/org/backends/README.org
  docs/org/backends/minic.org
  docs/org/backends/minihaskell.org
  docs/org/compiler-architecture/language/abstract.org
  docs/org/compiler-architecture/language/concrete.org
  docs/org/compiler-architecture/language/microjuvix.org
  docs/org/compiler-architecture/languages.org
  docs/org/compiler-architecture/pipeline.org
  docs/org/examples/README.org
  docs/org/examples/backend-specific/minic-hello-world.org
  docs/org/examples/validity-predicates/PolyFungibleToken.org
  docs/org/introduction/about/community.org
  docs/org/introduction/about/team.org
  docs/org/introduction/about/what-is.org
  docs/org/introduction/changelog.org
  docs/org/introduction/getting-started.org
  docs/org/language-reference/README.org
  docs/org/language-reference/axiom.org
  docs/org/language-reference/comments.org
  docs/org/language-reference/compile-blocks.org
  docs/org/language-reference/foreign-blocks.org
  docs/org/language-reference/functions.org
  docs/org/language-reference/inductive-data-types.org
  docs/org/language-reference/modules.org
  docs/org/language-reference/termination-checking.org
  docs/org/tooling/CLI.org
  docs/org/tooling/README.org
  docs/org/tooling/emacs-mode.org
  docs/org/tooling/testing.org
  tests/negative/Termination/Loop.mjuvix
Labels: documentation

#121 Only generates docs if the pull request merges
  .github/workflows/ci.yml
  docs/org/SUMMARY.org
  docs/org/notes/Monomorphization.org
  docs/org/notes/README.org
Labels: documentation

#125 Use Interval in GenericError; add flycheck support
  minijuvix-mode/flycheck-minijuvix.el
  src/MiniJuvix/Prelude/Error/GenericError.hs
  src/MiniJuvix/Syntax/Concrete/Parser/Error.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Error/Types.hs
  src/MiniJuvix/Syntax/MicroJuvix/Error/Types.hs
  src/MiniJuvix/Termination/Error/Types.hs
Labels: enhancement

#111 Add the termination checker to the pipeline
  app/GlobalOptions.hs
  app/Main.hs
  src/MiniJuvix/Pipeline.hs
  src/MiniJuvix/Pipeline/EntryPoint.hs
  src/MiniJuvix/Prelude/Base.hs
  src/MiniJuvix/Syntax/Abstract/AbstractResult.hs
  src/MiniJuvix/Syntax/Concrete/Parser.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Error/Types.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Scoper.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
  src/MiniJuvix/Termination/Checker.hs
  src/MiniJuvix/Termination/Error/Types.hs
  src/MiniJuvix/Translation/AbstractToMicroJuvix.hs
  src/MiniJuvix/Translation/ScopedToAbstract.hs
  test/BackendC/Positive.hs
  test/Base.hs
  test/Main.hs
  test/MonoJuvix/Positive.hs
  test/Scope/Negative.hs
  test/Scope/Positive.hs
  test/Termination.hs
  test/Termination/Negative.hs
  test/Termination/Positive.hs
  test/TypeCheck/Negative.hs
  test/TypeCheck/Positive.hs
  tests/negative/Termination/Data/Bool.mjuvix
  tests/negative/Termination/Data/Nat.mjuvix
  tests/negative/Termination/Data/QuickSort.mjuvix
  tests/negative/Termination/Data/Tree.mjuvix
  tests/negative/Termination/Mutual.mjuvix
  tests/negative/Termination/Ord.mjuvix
  tests/positive/Polymorphism.mjuvix
  tests/positive/Termination/Data/List.mjuvix
  tests/positive/Termination/Data/Maybe.mjuvix
  tests/positive/Termination/Data/Ord.mjuvix
  tests/positive/Termination/Data/Product.mjuvix
Labels: termination

#130 [app] Add compile command
  .gitignore
  app/CLI.hs
  app/Command.hs
  app/Commands/Compile.hs
  app/Main.hs
Labels: enhancement, CLI

#122 Add collaborative documentation
  docs/org/SUMMARY.org
  docs/org/backends/README.org
  docs/org/compiler-architecture/languages.org
  docs/org/examples/README.org
  docs/org/examples/validity-predicates/README.org
  docs/org/introduction/changelog.org
  docs/org/language-reference/README.org
  docs/org/language-reference/axiom.org
  docs/org/language-reference/compile-blocks.org
  docs/org/language-reference/foreign-blocks.org
  docs/org/language-reference/inductive-data-types.org
  docs/org/notes/README.org
  docs/org/notes/monomorphization.org
Labels: documentation

#133 Add "-Oz" optimization flag to clang args
  app/Commands/Compile.hs
Labels: enhancement, minic
