Repository anoma/juvix, pull requests merged in 2022-06, with the labels that each got.

#135 Revision for package.yaml and minor deletions
  .gitignore
  app/CLI.hs
  app/Command.hs
  app/Commands/Compile.hs
  app/Commands/Html.hs
  app/Commands/MicroJuvix.hs
  app/Commands/Scope.hs
  app/Commands/Termination.hs
  app/GlobalOptions.hs
  app/Main.hs
  package.yaml
  src/MiniJuvix/Prelude/Error/GenericError.hs
  src/MiniJuvix/Syntax/Concrete/Language/Stage.hs
  src/MiniJuvix/Syntax/Concrete/ModuleIsTop.hs
  test/BackendC/Positive.hs
Labels: haskell-package

#136 Add holes for expressions in function clauses and inference support
  docs/org/notes/monomorphization.org
  src/MiniJuvix/Syntax/Abstract/Language.hs
  src/MiniJuvix/Syntax/Abstract/Language/Extra.hs
  src/MiniJuvix/Syntax/Abstract/Pretty/Base.hs
  src/MiniJuvix/Syntax/Concrete/Language.hs
  src/MiniJuvix/Syntax/Concrete/Lexer.hs
  src/MiniJuvix/Syntax/Concrete/Parser.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Base.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Scoper.hs
  src/MiniJuvix/Syntax/Hole.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language/Extra.hs
  src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker/Inference.hs
  src/MiniJuvix/Termination/Checker.hs
  src/MiniJuvix/Translation/AbstractToMicroJuvix.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix/TypeCallsMapBuilder.hs
  src/MiniJuvix/Translation/ScopedToAbstract.hs
  test/BackendC/Positive.hs
  test/MonoJuvix/Positive.hs
  test/TypeCheck/Positive.hs
  tests/positive/FullExamples/PolySimpleFungibleTokenHoles.mjuvix
  tests/positive/MiniC/PolymorphismHoles/Input.mjuvix
  tests/positive/MiniC/PolymorphismHoles/expected.golden
  tests/positive/MiniC/PolymorphismHoles/minijuvix.yaml
  tests/positive/PolymorphismHoles.mjuvix
Labels: enhancement

#141 140 Support holes in type signatures
  src/MiniJuvix/Syntax/MicroJuvix/Error.hs
  src/MiniJuvix/Syntax/MicroJuvix/Error/Types.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language/Extra.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker/Inference.hs
  test/TypeCheck/Negative.hs
  test/TypeCheck/Positive.hs
  tests/negative/MicroJuvix/UnsolvedMeta.mjuvix
  tests/positive/MicroJuvix/HoleInSignature.mjuvix
  tests/positive/PolymorphismHoles.mjuvix
Labels: enhancement

#131 Add version and help option and root command to the CLI
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  Makefile
  app/App.hs
  app/CLI.hs
  app/Command.hs
  app/Commands/Compile.hs
  app/Commands/Extra.hs
  app/Commands/Html.hs
  app/Commands/MicroJuvix.hs
  app/Commands/MiniC.hs
  app/Commands/MiniHaskell.hs
  app/Commands/MonoJuvix.hs
  app/Commands/Parse.hs
  app/Commands/Scope.hs
  app/Commands/Termination.hs
  app/GlobalOptions.hs
  app/Main.hs
  minijuvix-mode/flycheck-minijuvix.el
  src/MiniJuvix/Syntax/Abstract/Pretty/Base.hs
  src/MiniJuvix/Syntax/Abstract/Pretty/Options.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Base.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Options.hs
  src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/MiniJuvix/Syntax/MicroJuvix/Pretty/Options.hs
  tests/CLI/Commands/compile.test
  tests/CLI/Commands/microjuvix.test
  tests/CLI/Commands/minic.test
  tests/CLI/Commands/minihaskell.test
  tests/CLI/Commands/monojuvix.test
  tests/CLI/Commands/parse.test
  tests/CLI/Commands/root.test
  tests/CLI/Commands/scope.test
  tests/CLI/Commands/termination.test
  tests/CLI/help.test
  tests/CLI/version.test
Labels: enhancement, CLI

#137 Support function closures with no environment in minic
  minic-runtime/anoma/anoma.h
  minic-runtime/libc/minic-runtime.h
  minic-runtime/standalone/minic-runtime.h
  src/MiniJuvix/Internal/Strings.hs
  src/MiniJuvix/Syntax/MiniC/Language.hs
  src/MiniJuvix/Syntax/MiniC/Serialization.hs
  src/MiniJuvix/Syntax/MonoJuvix/Language.hs
  src/MiniJuvix/Translation/MonoJuvixToMiniC.hs
  test/BackendC/Positive.hs
  tests/positive/MiniC/ClosureNoEnv/IO.mjuvix
  tests/positive/MiniC/ClosureNoEnv/Input.mjuvix
  tests/positive/MiniC/ClosureNoEnv/String.mjuvix
  tests/positive/MiniC/ClosureNoEnv/expected.golden
  tests/positive/MiniC/ClosureNoEnv/minijuvix.yaml
Labels: enhancement, minic

#153 Add positive test designed for implicit arguments
  test/TypeCheck/Positive.hs
  tests/positive/MicroJuvix/Implicit.mjuvix
Labels: test-suite

#156 Remove dead code related to the pipeline
  src/MiniJuvix/Pipeline.hs
  src/MiniJuvix/Pipeline/Stage.hs
Labels: refactor

#154 Add negative test for AppLeftImplicit
  test/Scope/Negative.hs
  tests/negative/AppLeftImplicit.mjuvix
Labels: test-suite

#158 Update README usage example to use the compile command
  README.org
Labels: documentation

#163 Fix links in documentation and update to new syntax
  README.org
  docs/org/SUMMARY.org
  docs/org/examples/backend-specific/minic-hello-world.org
  docs/org/examples/validity-predicates/PolyFungibleToken.org
  docs/org/getting-started/README.org
  docs/org/getting-started/dependencies.org
  docs/org/getting-started/quick-start.org
  docs/org/tooling/testing.org
Labels: documentation

#165 Allow holes to be refined into function types
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker/Inference.hs
  tests/positive/MicroJuvix/Implicit.mjuvix
Labels: enhancement, typechecking, holes

#170 Improve filepath equality
  app/CLI.hs
  src/MiniJuvix/Prelude/Files.hs
  test/Scope/Positive.hs
Labels: refactor

#173 Remove TypeAny and adapt typechecking for literals
  src/MiniJuvix/Internal/Strings.hs
  src/MiniJuvix/Syntax/MicroJuvix/ArityChecker.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language/Extra.hs
  src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker/Inference.hs
  src/MiniJuvix/Syntax/MonoJuvix/Language.hs
  src/MiniJuvix/Syntax/MonoJuvix/Pretty/Base.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix/TypeCallsMapBuilder.hs
  src/MiniJuvix/Translation/MonoJuvixToMiniC.hs
  src/MiniJuvix/Translation/MonoJuvixToMiniHaskell.hs
Labels: enhancement, refactor

#172 Ignore implicit patterns and arguments in termination checking
  src/MiniJuvix/Termination/FunctionCall.hs
  src/MiniJuvix/Termination/Types/SizeInfo.hs
  tests/positive/Termination/Data/Bool.mjuvix
  tests/positive/Termination/Data/List.mjuvix
Labels: bug

#171 Fix: identifiers with a keyword prefix cannot be parsed
  src/MiniJuvix/Syntax/Concrete/Lexer.hs
  test/Scope/Positive.hs
  tests/positive/Parsing.mjuvix
Labels: bug:parsing

#175 Allow `open import` statements
  src/MiniJuvix/Syntax/Concrete/Language.hs
  src/MiniJuvix/Syntax/Concrete/Parser.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Base.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Scoper.hs
  src/MiniJuvix/Translation/ScopedToAbstract.hs
  tests/positive/MiniC/MultiModules/Input.mjuvix
  tests/positive/MiniC/MultiModules/Prelude.mjuvix
Labels: enhancement

#176 Embed HTML assets in the minijuvix binary
  src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Html.hs
  src/MiniJuvix/Utils/Paths.hs
Labels: html, app

#177 Replace dead link in README with a link to the MiniJuvix book
  README.org
Labels: documentation

#143 Remove ExpressionTyped from MicroJuvix
  src/MiniJuvix/Syntax/MicroJuvix/ArityChecker.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language/Extra.hs
  src/MiniJuvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix/TypeCallsMapBuilder.hs
  tests/positive/MiniC/Polymorphism/Input.mjuvix
  tests/positive/MiniC/Polymorphism/expected.golden
Labels: refactor

#181 Use Abstract name in Abstract syntax and Micro/MonoJuvix
  app/Main.hs
  src/MiniJuvix/Syntax/Abstract/InfoTableBuilder.hs
  src/MiniJuvix/Syntax/Abstract/Language.hs
  src/MiniJuvix/Syntax/Abstract/Language/Extra.hs
  src/MiniJuvix/Syntax/Abstract/Name.hs
  src/MiniJuvix/Syntax/Abstract/Pretty/Base.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language.hs
  src/MiniJuvix/Syntax/MicroJuvix/TypeChecker.hs
  src/MiniJuvix/Syntax/MonoJuvix/Language.hs
  src/MiniJuvix/Termination/Checker.hs
  src/MiniJuvix/Termination/Error/Types.hs
  src/MiniJuvix/Termination/FunctionCall.hs
  src/MiniJuvix/Termination/LexOrder.hs
  src/MiniJuvix/Termination/Types/FunctionCall.hs
  src/MiniJuvix/Termination/Types/Graph.hs
  src/MiniJuvix/Translation/AbstractToMicroJuvix.hs
  src/MiniJuvix/Translation/MicroJuvixToMonoJuvix.hs
  src/MiniJuvix/Translation/ScopedToAbstract.hs
Labels: refactor

#178 Upgrade to ghc-9.2.3
  .github/workflows/ci.yml
  stack.yaml
Labels: build

#179 Add an option to specify the path where to put the HTML output
  app/Commands/Html.hs
  app/Main.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Pretty/Html.hs
  tests/CLI/Commands/html.test
Labels: CLI, html, app

#182 Fix: Add check for constructor return types
  src/MiniJuvix/Pipeline.hs
  src/MiniJuvix/Syntax/MicroJuvix/Error.hs
  src/MiniJuvix/Syntax/MicroJuvix/Error/Types.hs
  src/MiniJuvix/Syntax/MicroJuvix/Language/Extra.hs
  src/MiniJuvix/Translation/AbstractToMicroJuvix.hs
  test/TypeCheck/Negative.hs
  tests/negative/MicroJuvix/FunctionApplied.mjuvix
  tests/negative/MicroJuvix/WrongReturnType.mjuvix
  tests/negative/MicroJuvix/WrongReturnTypeParameters.mjuvix
  tests/positive/Polymorphism.mjuvix
  tests/positive/PolymorphismHoles.mjuvix
Labels: typechecking, fix:bug

#209 Update project description v0.2.0
  README.org
  docs/org/introduction/about/what-is.org
Labels: documentation

#211 README: Include `--recursive` in git clone command to fetch stdlib
  README.org
  docs/org/getting-started/quick-start.org
Labels: documentation
