Repository anoma/juvix, pull requests merged in 2022-07, with the labels that each got.

#1320 Add Version number to the emacs mode
  juvix-mode/juvix-mode.el
Labels: emacs-mode

#1375 Add fibonacci sequence example program
  examples/milestone/Fibonacci/Fibonacci.juvix
  test/BackendC/Base.hs
  test/BackendC/Examples.hs
  tests/examplesExpected/Fibonacci/expected.golden
Labels: documentation

#1377 Check all the type parameter names are different when declaring an inductive type
  src/Juvix/Syntax/Concrete/Scoped/Error.hs
  src/Juvix/Syntax/Concrete/Scoped/Error/Types.hs
  src/Juvix/Syntax/Concrete/Scoped/Scoper.hs
  test/Scope/Negative.hs
  tests/negative/DuplicateInductiveParameterName.juvix
Labels: enhancement

#1384 Adds Collatz sequence generator example
  examples/milestone/Collatz/Collatz.juvix
  test/BackendC/Examples.hs
  tests/examplesExpected/Collatz/expected.golden
Labels: documentation

#1381 html-examples
  .github/workflows/ci.yml
  Makefile
Labels: CI, documentation, html

#1387 Fix documentation generation
  .github/workflows/ci.yml
  Makefile
Labels: documentation

#1378 Type checking fails when the type of a pattern is not given by the signature
  src/Juvix/Syntax/MicroJuvix/Error/Types.hs
  src/Juvix/Syntax/MicroJuvix/TypeChecker.hs
  src/Juvix/Syntax/MicroJuvix/TypeChecker/Inference.hs
  test/TypeCheck/Negative.hs
  test/TypeCheck/Positive.hs
  tests/negative/265/M.juvix
  tests/negative/265/juvix.yaml
  tests/positive/265/M.juvix
  tests/positive/265/juvix.yaml
Labels: typechecking

#1385 Widens the accepted symbol list
  src/Juvix/Syntax/Concrete/Lexer.hs
  test/Scope/Positive.hs
  tests/positive/Symbols.juvix
Labels: enhancement

#1386 Direct translation from MicroJuvix to MiniC
  app/Main.hs
  src/Juvix/Pipeline.hs
  src/Juvix/Syntax/MicroJuvix/InfoTable.hs
  src/Juvix/Syntax/MicroJuvix/Language.hs
  src/Juvix/Syntax/MicroJuvix/Language/Extra.hs
  src/Juvix/Syntax/MicroJuvix/MicroJuvixTypedResult.hs
  src/Juvix/Syntax/MicroJuvix/TypeChecker.hs
  src/Juvix/Syntax/MicroJuvix/TypeChecker/Inference.hs
  src/Juvix/Translation/MicroJuvixToMiniC.hs
  src/Juvix/Translation/MicroJuvixToMiniC/Base.hs
  src/Juvix/Translation/MicroJuvixToMiniC/BuiltinTable.hs
  src/Juvix/Translation/MicroJuvixToMiniC/CBuilder.hs
  src/Juvix/Translation/MicroJuvixToMiniC/CNames.hs
  src/Juvix/Translation/MicroJuvixToMiniC/Closure.hs
  src/Juvix/Translation/MicroJuvixToMiniC/Types.hs
  src/Juvix/Translation/MonoJuvixToMiniC/Base.hs
  test/BackendC/Base.hs
  test/BackendC/Positive.hs
  tests/positive/MiniC/PolymorphicAxioms/Input.juvix
  tests/positive/MiniC/PolymorphicAxioms/expected.golden
  tests/positive/MiniC/PolymorphicAxioms/juvix.yaml
  tests/positive/MiniC/PolymorphicTarget/Input.juvix
  tests/positive/MiniC/PolymorphicTarget/expected.golden
  tests/positive/MiniC/PolymorphicTarget/juvix.yaml
Labels: enhancement

#1391 Update some docs
  .gitignore
  Makefile
  README.org
  docs/org/SUMMARY.org
  docs/org/examples/README.org
  docs/org/examples/backend-specific/minic-hello-world.org
  docs/org/examples/validity-predicates/README.org
  docs/org/getting-started/dependencies.org
  docs/org/getting-started/quick-start.org
  docs/org/introduction/about/what-is.org
  docs/org/language-reference/axiom.org
  docs/org/language-reference/builtins.org
  docs/org/language-reference/comments.org
  docs/org/language-reference/compile-blocks.org
  docs/org/language-reference/foreign-blocks.org
  docs/org/language-reference/inductive-data-types.org
  docs/org/language-reference/modules.org
  docs/org/language-reference/termination-checking.org
  docs/org/tooling/CLI.org
  docs/org/tooling/emacs-mode.org
Labels: documentation

#1380 Curly braces are allowed nested in patterns
  src/Juvix/Syntax/Abstract/Language.hs
  src/Juvix/Syntax/Abstract/Language/Extra.hs
  src/Juvix/Syntax/Concrete/Language.hs
  src/Juvix/Syntax/Concrete/Scoped/Pretty/Base.hs
  src/Juvix/Syntax/Concrete/Scoped/Scoper.hs
  src/Juvix/Syntax/IsImplicit.hs
  src/Juvix/Syntax/MicroJuvix/ArityChecker.hs
  src/Juvix/Syntax/MicroJuvix/ArityChecker/Error.hs
  src/Juvix/Syntax/MicroJuvix/ArityChecker/Error/Types.hs
  src/Juvix/Syntax/MicroJuvix/Language.hs
  src/Juvix/Syntax/MicroJuvix/Language/Extra.hs
  src/Juvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/Juvix/Syntax/MicroJuvix/TypeChecker.hs
  src/Juvix/Termination/FunctionCall.hs
  src/Juvix/Termination/Types/SizeInfo.hs
  src/Juvix/Translation/AbstractToMicroJuvix.hs
  src/Juvix/Translation/MicroJuvixToMiniC.hs
  src/Juvix/Translation/MicroJuvixToMiniC/Base.hs
  src/Juvix/Translation/MicroJuvixToMonoJuvix.hs
  src/Juvix/Translation/ScopedToAbstract.hs
  test/Arity/Negative.hs
  test/TypeCheck/Negative.hs
  tests/negative/258/M.juvix
  tests/negative/258/juvix.yaml
  tests/negative/issue1337/Braces.juvix
  tests/negative/issue1337/juvix.yaml
Labels: bug, language, syntax

#1402 Replace ppSimple by text
  src/Juvix/Builtins/Natural.hs
  src/Juvix/Syntax/Abstract/Pretty.hs
  src/Juvix/Syntax/MicroJuvix/Pretty.hs
Labels: refactor

#1403 Use bold for code in scoper error messages
  src/Juvix/Syntax/Concrete/Scoped/Error/Pretty.hs
  src/Juvix/Syntax/Concrete/Scoped/Error/Pretty/Ansi.hs
  src/Juvix/Syntax/Concrete/Scoped/Error/Types.hs
Labels: error-messaging

#1392 Keep qualified names
  src/Juvix/Syntax/Abstract/Language/Extra.hs
  src/Juvix/Syntax/Abstract/Name.hs
  src/Juvix/Syntax/Abstract/Pretty/Ann.hs
  src/Juvix/Syntax/Abstract/Pretty/Base.hs
  src/Juvix/Syntax/Concrete/Name.hs
  src/Juvix/Syntax/Concrete/Scoped/Name.hs
  src/Juvix/Syntax/Concrete/Scoped/Name/NameKind.hs
  src/Juvix/Syntax/MicroJuvix/Pretty/Ann.hs
  src/Juvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/Juvix/Syntax/MicroJuvix/TypeChecker.hs
  src/Juvix/Translation/MicroJuvixToMonoJuvix.hs
  src/Juvix/Translation/ScopedToAbstract.hs
  tests/negative/issue1344/D.juvix
  tests/negative/issue1344/M.juvix
  tests/negative/issue1344/Other.juvix
  tests/negative/issue1344/U.juvix
  tests/negative/issue1344/errorD.test
  tests/negative/issue1344/errorM.test
  tests/negative/issue1344/juvix.yaml
Labels: enhancement, error-messaging

#1393 Add positivity check for data types
  app/GlobalOptions.hs
  app/Main.hs
  docs/org/SUMMARY.org
  docs/org/notes/strictly-positive-data-types.org
  src/Juvix/Analysis/Positivity/Checker.hs
  src/Juvix/Internal/Strings.hs
  src/Juvix/Pipeline/EntryPoint.hs
  src/Juvix/Syntax/Abstract/Language.hs
  src/Juvix/Syntax/Concrete/Language.hs
  src/Juvix/Syntax/Concrete/Lexer.hs
  src/Juvix/Syntax/Concrete/Parser.hs
  src/Juvix/Syntax/Concrete/Scoped/Scoper.hs
  src/Juvix/Syntax/MicroJuvix/Error.hs
  src/Juvix/Syntax/MicroJuvix/Error/Types.hs
  src/Juvix/Syntax/MicroJuvix/InfoTable.hs
  src/Juvix/Syntax/MicroJuvix/Language.hs
  src/Juvix/Syntax/MicroJuvix/Language/Extra.hs
  src/Juvix/Syntax/MicroJuvix/MicroJuvixArityResult.hs
  src/Juvix/Syntax/MicroJuvix/MicroJuvixResult.hs
  src/Juvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/Juvix/Syntax/MicroJuvix/TypeChecker.hs
  src/Juvix/Syntax/Universe.hs
  src/Juvix/Translation/AbstractToMicroJuvix.hs
  src/Juvix/Translation/MicroJuvixToMiniC.hs
  src/Juvix/Translation/MicroJuvixToMonoJuvix.hs
  src/Juvix/Translation/MicroJuvixToMonoJuvix/TypeCallsMapBuilder.hs
  src/Juvix/Translation/ScopedToAbstract.hs
  test/Scope/Positive.hs
  test/Termination/Positive.hs
  test/TypeCheck/Negative.hs
  test/TypeCheck/Positive.hs
  tests/CLI/help.test
  tests/negative/MicroJuvix/Positivity/E1.juvix
  tests/negative/MicroJuvix/Positivity/E2.juvix
  tests/negative/MicroJuvix/Positivity/E3.juvix
  tests/negative/MicroJuvix/Positivity/E4.juvix
  tests/negative/MicroJuvix/Positivity/E5.juvix
  tests/negative/MicroJuvix/Positivity/E6.juvix
  tests/negative/MicroJuvix/Positivity/E7.juvix
  tests/negative/MicroJuvix/Positivity/E8.juvix
  tests/negative/MicroJuvix/Positivity/E9.juvix
  tests/negative/MicroJuvix/Positivity/NegParam.juvix
  tests/negative/MicroJuvix/Positivity/errorE5.test
  tests/negative/MicroJuvix/Positivity/errorE9.test
  tests/negative/MicroJuvix/Positivity/juvix.yaml
  tests/positive/MicroJuvix/Positivity/E5.juvix
  tests/positive/MicroJuvix/Positivity/juvix.yaml
Labels: enhancement, CLI, typechecking

#1404 Support type aliases
  src/Juvix/Analysis/Positivity/Checker.hs
  src/Juvix/Prelude/Base.hs
  src/Juvix/Syntax/MicroJuvix/ArityChecker.hs
  src/Juvix/Syntax/MicroJuvix/InfoTable.hs
  src/Juvix/Syntax/MicroJuvix/Language.hs
  src/Juvix/Syntax/MicroJuvix/Language/Extra.hs
  src/Juvix/Syntax/MicroJuvix/Pretty/Base.hs
  src/Juvix/Syntax/MicroJuvix/TypeChecker.hs
  src/Juvix/Syntax/MicroJuvix/TypeChecker/FunctionsTable.hs
  src/Juvix/Syntax/MicroJuvix/TypeChecker/Inference.hs
  src/Juvix/Translation/AbstractToMicroJuvix.hs
  src/Juvix/Translation/MicroJuvixToMiniC.hs
  src/Juvix/Translation/MicroJuvixToMiniC/Base.hs
  src/Juvix/Translation/MicroJuvixToMiniC/Closure.hs
  src/Juvix/Translation/MicroJuvixToMonoJuvix.hs
  src/Juvix/Translation/MicroJuvixToMonoJuvix/TypeCallsMapBuilder.hs
  test/TypeCheck/Negative.hs
  test/TypeCheck/Positive.hs
  tests/negative/MicroJuvix/Positivity/E10.juvix
  tests/negative/MicroJuvix/Positivity/E11.juvix
  tests/positive/MiniC/MutuallyRecursive/Input.juvix
  tests/positive/TypeAlias.juvix
  tests/positive/issue1333/M.juvix
  tests/positive/issue1333/juvix.yaml
Labels: enhancement, typechecking

#1411 Add `Fail` effect (#1409)
  src/Juvix/Analysis/TypeChecking/Inference.hs
  src/Juvix/Prelude.hs
  src/Juvix/Prelude/Base.hs
  src/Juvix/Prelude/Effect/Fail.hs
  test/Base.hs
Labels: refactor

#1408 Compute name dependency graph and filter unreachable definitions
  package.yaml
  src/Juvix/Analysis/Scoping/Scoper.hs
  src/Juvix/Analysis/Scoping/ScoperResult.hs
  src/Juvix/DependencyInfo.hs
  src/Juvix/Pipeline.hs
  src/Juvix/Syntax/Abstract/AbstractResult.hs
  src/Juvix/Syntax/Abstract/DependencyBuilder.hs
  src/Juvix/Syntax/Abstract/NameDependencyInfo.hs
  src/Juvix/Syntax/MicroJuvix/MicroJuvixResult.hs
  src/Juvix/Syntax/MicroJuvix/Reachability.hs
  src/Juvix/Translation/AbstractToMicroJuvix.hs
  src/Juvix/Translation/ScopedToAbstract.hs
  test/Main.hs
  test/Reachability.hs
  test/Reachability/Positive.hs
  tests/positive/Reachability/Data/Bool.juvix
  tests/positive/Reachability/Data/Maybe.juvix
  tests/positive/Reachability/Data/Nat.juvix
  tests/positive/Reachability/Data/Ord.juvix
  tests/positive/Reachability/Data/Product.juvix
  tests/positive/Reachability/M.juvix
  tests/positive/Reachability/N.juvix
  tests/positive/Reachability/O.juvix
  tests/positive/Reachability/juvix.yaml
Labels: enhancement

#1415 Fix version shell test for 0.2.2
  tests/CLI/version.test
Labels: test-suite

#1418 Permit axiom without a compile block
  src/Juvix/Translation/MicroJuvixToMiniC.hs
  test/BackendC/Positive.hs
  tests/positive/MiniC/AxiomNoCompile/Input.juvix
  tests/positive/MiniC/AxiomNoCompile/expected.golden
  tests/positive/MiniC/AxiomNoCompile/juvix.yaml
Labels: c-backend

#1422 add `name` and `version` to `juvix.yaml`
  app/Main.hs
  examples/milestone/MiniTicTacToe/juvix.yaml
  package.yaml
  src/Juvix/Documentation/Compiler.hs
  src/Juvix/Pipeline/EntryPoint.hs
  src/Juvix/Pipeline/Package.hs
  test/Reachability/Positive.hs
  test/Scope/Positive.hs
  test/Termination/Positive.hs
  test/TypeCheck/Positive.hs
Labels: enhancement, CLI, html
