Repository anoma/juvix, pull requests merged in 2022-07, with the labels that each got.

#223 Perform ScopedToAbstract exactly once for each module
  src/MiniJuvix/Translation/ScopedToAbstract.hs
  test/TypeCheck/Positive.hs
  tests/positive/BuiltinsMultiImport/A.mjuvix
  tests/positive/BuiltinsMultiImport/Input.mjuvix
  tests/positive/BuiltinsMultiImport/Nat.mjuvix
  tests/positive/BuiltinsMultiImport/minijuvix.yaml
Labels: bug

#224 Use the ModulesCache for `open` statements in ScopedToAbstract pass
  src/MiniJuvix/Translation/ScopedToAbstract.hs
  test/TypeCheck/Positive.hs
  tests/positive/BuiltinsMultiOpenImport/A.mjuvix
  tests/positive/BuiltinsMultiOpenImport/Input.mjuvix
  tests/positive/BuiltinsMultiOpenImport/Nat.mjuvix
  tests/positive/BuiltinsMultiOpenImport/minijuvix.yaml
Labels: fix:bug

#234 Filter symbol entries properly in the scoper
  src/MiniJuvix/Syntax/Concrete/Language.hs
  src/MiniJuvix/Syntax/Concrete/Scoped/Scoper.hs
  test/Scope/Negative.hs
  tests/negative/230/Foo.mjuvix
  tests/negative/230/Foo/Data/Bool.mjuvix
  tests/negative/230/Prod.mjuvix
  tests/negative/230/minijuvix.yaml
Labels: bug:scoping

#237 Fixed a bug with the path to walloc.c
  app/Commands/Compile.hs
Labels: minic, bug

#239 Add option to disable minijuvix input method
  minijuvix-mode/minijuvix-input.el
  minijuvix-mode/minijuvix-mode.el
Labels: emacs-mode

#244 Deprecate GHC backend
  app/Command.hs
Labels: CLI

#243 Throw error when reading a file that conflicts with embedded stdlib
  src/MiniJuvix/Pipeline.hs
  src/MiniJuvix/Prelude/Files.hs
  src/MiniJuvix/Prelude/Files/Error.hs
  test/Scope/Negative.hs
  test/Termination/Positive.hs
  tests/negative/StdlibConflict/Data/Bool.mjuvix
  tests/negative/StdlibConflict/Input.mjuvix
  tests/negative/StdlibConflict/minijuvix.yaml
Labels: enhancement, error-messaging

#247 Add emacs option `minijuvix-disable-embedded-stdlib`
  minijuvix-mode/flycheck-minijuvix.el
  minijuvix-mode/minijuvix-customize.el
  minijuvix-mode/minijuvix-mode.el
Labels: emacs-mode

#248 Restore Juvix mascot image to README
  .pre-commit-config.yaml
  README.org
  assets/seating-mascot.051c86a.svg
Labels: documentation

#250 Restore mascot images to the minijuvix book
  Makefile
  assets/Seating_Tara_smiling.svg
  assets/teaching-mascot.f828959.svg
  docs/org/getting-started/quick-start.org
  docs/org/introduction/about/what-is.org
  docs/org/introduction/changelog.org
Labels: documentation

#252 Enforce C99 standard in the generated C files
  app/Commands/Compile.hs
  test/BackendC/Base.hs
Labels: CLI, c-backend

#260 Include `open import` statements when generating HTML
  src/Juvix/Syntax/Concrete/Scoped/Utils.hs
Labels: html

#261 Add issues and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: enhancement

#270 Specialize commands of/for internal use
  app/Command.hs
  app/Commands/Extra.hs
  app/Commands/Internal.hs
  app/Commands/Internal/MicroJuvix.hs
  app/Commands/Internal/Parse.hs
  app/Commands/Internal/Scope.hs
  app/Commands/Internal/Termination.hs
  app/Main.hs
  juvix-mode/flycheck-juvix.el
  juvix-mode/juvix-input.el
  juvix-mode/juvix-mode.el
  tests/CLI/Commands/internals/microjuvix.test
  tests/CLI/Commands/internals/minic.test
  tests/CLI/Commands/internals/minihaskell.test
  tests/CLI/Commands/internals/monojuvix.test
  tests/CLI/Commands/internals/parse.test
  tests/CLI/Commands/internals/root.test
  tests/CLI/Commands/internals/scope.test
  tests/CLI/Commands/internals/termination.test
  tests/CLI/Commands/microjuvix.test
  tests/CLI/Commands/minic.test
  tests/CLI/Commands/minihaskell.test
  tests/CLI/Commands/monojuvix.test
  tests/CLI/Commands/parse.test
  tests/CLI/Commands/scope.test
  tests/CLI/Commands/termination.test
  tests/CLI/Commands/typecheck.test
Labels: enhancement, CLI
