Repository anoma/juvix, pull requests merged in 2022-08, with the labels that each got.

#1429 Do not add `-src` suffix to links in HTML when running `juvix html`
  src/Juvix/Documentation/Compiler.hs
  src/Juvix/Syntax/Concrete/Scoped/Pretty/Html.hs
Labels: html

#1426 WASM import all non-compile axioms with alphanum names in entrypoint
  docs/org/SUMMARY.org
  docs/org/tutorials/README.org
  docs/org/tutorials/nodejs-interop.org
  src/Juvix/Syntax/MiniC/Language.hs
  src/Juvix/Syntax/MiniC/Serialization.hs
  src/Juvix/Translation/MicroJuvixToMiniC.hs
  test/BackendC/Base.hs
  test/BackendC/Positive.hs
  test/Base.hs
  tests/positive/MiniC/ImportExportName/Input.juvix
  tests/positive/MiniC/ImportExportName/expected.golden
  tests/positive/MiniC/ImportExportName/input.js
  tests/positive/MiniC/ImportExportName/juvix.yaml
Labels: c-backend

#1427 Add a Web version of TicTacToe
  .github/workflows/ci.yml
  Makefile
  README.org
  docs/org/examples/README.org
  examples/milestone/MiniTicTacToe/juvix.yaml
  examples/milestone/TicTacToe/CLI/TicTacToe.juvix
  examples/milestone/TicTacToe/Logic/Game.juvix
  examples/milestone/TicTacToe/Web/TicTacToe.juvix
  examples/milestone/TicTacToe/Web/index.html
  examples/milestone/TicTacToe/Web/ticTacToe.js
  examples/milestone/TicTacToe/juvix.yaml
  test/BackendC/Examples.hs
  tests/examplesExpected/TicTacToe/expected.golden
Labels: documentation

#1433 Setup Clang before building docs in CI
  .github/workflows/ci.yml
  Makefile
  examples/milestone/TicTacToe/Web/index.html
  examples/milestone/TicTacToe/Web/tictactoe.js
Labels: documentation

#1434 Various documentation adjustments
  README.org
  docs/org/SUMMARY.org
  docs/org/introduction/about/community.org
  docs/org/language-reference/functions.org
  docs/org/language-reference/inductive-data-types.org
  docs/org/language-reference/termination-checking.org
  examples/milestone/ValidityPredicates/SimpleFungibleToken.juvix
Labels: documentation

#1435 CI checkout repo before cache and use recommended cache strategy
  .github/workflows/ci.yml
Labels: CI

#1437 CI: Run build on push to main
  .github/workflows/ci.yml
Labels: CI

#1440 Add revisions to README
  README.org
Labels: documentation

#1436 Add doctor subcommand
  app/CLI.hs
  app/Command.hs
  app/Commands/Doctor.hs
  app/Main.hs
  docs/org/SUMMARY.org
  docs/org/tooling/README.org
  docs/org/tooling/doctor.org
  package.yaml
  src/Juvix/Data/Effect.hs
  src/Juvix/Data/Effect/Fail.hs
  src/Juvix/Data/Effect/Log.hs
  tests/CLI/doctor.test
  tests/CLI/help.test
Labels: CLI

#1442 Add initial support for examples in Html documentation
  app/Main.hs
  examples/milestone/TicTacToe/Logic/Game.juvix
  src/Juvix/Compiler/Abstract/Language.hs
  src/Juvix/Compiler/Abstract/Translation/FromConcrete.hs
  src/Juvix/Compiler/Backend/Haskell/Pretty/Base.hs
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped.hs
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped/Source.hs
  src/Juvix/Compiler/Builtins/Natural.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Pretty/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource/Lexer.hs
  src/Juvix/Compiler/Internal/Extra.hs
  src/Juvix/Compiler/Internal/Language.hs
  src/Juvix/Compiler/Internal/Pretty.hs
  src/Juvix/Compiler/Internal/Translation/FromAbstract.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/ArityChecking/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/ArityChecking/Data/Context.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Data/Context.hs
  src/Juvix/Compiler/Mono/Translation/FromInternal.hs
  src/Juvix/Compiler/Pipeline.hs
  src/Juvix/Extra/Process.hs
  src/Juvix/Extra/Strings.hs
  src/Juvix/Prelude/Base.hs
  src/Juvix/Prelude/Pretty.hs
Labels: judoc

#1447 Properly handle paragraphs in judoc
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped.hs
Labels: bug, judoc

#1446 Add Towers of Hanoi and Pascal triangle examples
  Makefile
  README.org
  docs/org/examples/README.org
  examples/milestone/Hanoi/Hanoi.juvix
  examples/milestone/Hanoi/juvix.yaml
  examples/milestone/PascalsTriangle/PascalsTriangle.juvix
  examples/milestone/PascalsTriangle/juvix.yaml
  test/BackendC/Examples.hs
  tests/examplesExpected/Hanoi/expected.golden
  tests/examplesExpected/PascalsTriangle/expected.golden
Labels: documentation

#1445 Add `juvix init` command
  app/CLI.hs
  app/Commands/Init.hs
  app/Main.hs
  package.yaml
  src/Juvix/Compiler/Pipeline/Package.hs
  src/Juvix/Data/Effect/Fail/Extra.hs
Labels: CLI

#1450 Add the option to output json in the `juvix internal highlight` command
  app/App.hs
  app/Commands/Dev.hs
  app/Main.hs
  src/Juvix/Compiler/Concrete/Data/Highlight.hs
  src/Juvix/Compiler/Concrete/Data/Highlight/Input.hs
  src/Juvix/Compiler/Concrete/Data/Highlight/Properties.hs
  src/Juvix/Compiler/Concrete/Data/Highlight/SExp.hs
  src/Juvix/Data/Loc.hs
  src/Juvix/Prelude/Base.hs
Labels: CLI, highlight

#1449 Allow _ in Wasm exported names to support Anoma signature
  c-runtime/standalone/c-runtime.h
  c-runtime/wasi-libc/c-runtime.h
  c-runtime/wasi-standalone/c-runtime.h
  src/Juvix/Compiler/Backend/C/Translation/FromInternal.hs
  test/BackendC/Positive.hs
  tests/positive/MiniC/AlwaysValidVP/Input.juvix
  tests/positive/MiniC/AlwaysValidVP/expected.golden
  tests/positive/MiniC/AlwaysValidVP/input.js
  tests/positive/MiniC/AlwaysValidVP/juvix.yaml
Labels: c-backend

#1453 Give a proper type to literal natural numbers
  examples/milestone/ValidityPredicates/Anoma/Base.juvix
  examples/milestone/ValidityPredicates/Data/Int.juvix
  examples/milestone/ValidityPredicates/SimpleFungibleToken.juvix
  src/Juvix/Compiler/Internal/Translation/FromInternal.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/ArityChecking/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Checker.hs
  src/Juvix/Compiler/Pipeline.hs
  tests/positive/FullExamples/MonoSimpleFungibleToken.juvix
  tests/positive/FullExamples/SimpleFungibleTokenImplicit.juvix
  tests/positive/Internal/LiteralInt.juvix
  tests/positive/MiniC/AlwaysValidVP/Input.juvix
  tests/positive/MiniC/Builtins/Input.juvix
  tests/positive/MiniC/ClosureEnv/Input.juvix
  tests/positive/MiniC/ClosureNoEnv/Input.juvix
  tests/positive/MiniC/HigherOrder/Input.juvix
  tests/positive/MiniC/MultiModules/Data/Int.juvix
  tests/positive/MiniC/MultiModules/Data/Nat.juvix
  tests/positive/MiniC/MutuallyRecursive/Data/Int.juvix
  tests/positive/MiniC/MutuallyRecursive/Data/Nat.juvix
  tests/positive/MiniC/MutuallyRecursive/Input.juvix
  tests/positive/MiniC/Nat/Input.juvix
  tests/positive/MiniC/PolymorphicTarget/Input.juvix
  tests/positive/MiniC/SimpleFungibleTokenImplicit/Input.juvix
Labels: typechecking

#1454 Fixes TicTacToe Web example
  examples/milestone/TicTacToe/Web/TicTacToe.juvix
  test/BackendC/Base.hs
  test/BackendC/Examples.hs
Labels: documentation

#1456 Small changes for the presentation
  assets/linuwial.css
  examples/milestone/TicTacToe/CLI/TicTacToe.juvix
  examples/milestone/TicTacToe/Logic/Board.juvix
  examples/milestone/TicTacToe/Logic/Extra.juvix
  examples/milestone/TicTacToe/Logic/Game.juvix
  examples/milestone/TicTacToe/Logic/GameState.juvix
  examples/milestone/TicTacToe/Logic/Square.juvix
  examples/milestone/TicTacToe/Logic/Symbol.juvix
  examples/milestone/TicTacToe/TicTacToe.juvix
  examples/milestone/TicTacToe/juvix.yaml
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped.hs
  src/Juvix/Compiler/Concrete/Pretty/Base.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Checker.hs
Labels: documentation

#1458 Fix typechecker
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Data/Inference.hs
Labels: error-messaging, bug, typechecking

#1457 Add a native compile target for demos
  app/Commands/Compile.hs
  tests/CLI/Commands/compile.test
Labels: c-backend

#1459 Add --stdin flag
  app/GlobalOptions.hs
  app/Main.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Pipeline/EntryPoint.hs
  test/Reachability/Positive.hs
  test/Scope/Positive.hs
  test/Termination/Positive.hs
  test/TypeCheck/Positive.hs
  tests/CLI/help.test
Labels: enhancement, CLI

#1460 use --stdin in flycheck mode
  juvix-mode/flycheck-juvix.el
Labels: emacs-mode

#1472 Properly type check patterns that need normalization
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Data/Inference.hs
  test/TypeCheck/Positive.hs
  tests/positive/issue1466/M.juvix
  tests/positive/issue1466/juvix.yaml
Labels: bug, typechecking

#1488 Add a github action to build a static linux binary
  .github/workflows/linux-static-binary.yaml
  docker/Dockerfile-ghc-alpine-9.2.4
Labels: CI

#1492 Add --allow-different-user to workflow stack command
  .github/workflows/linux-static-binary.yaml
Labels: CI

#1489 Restructure recursors and add some lens interfaces
  src/Juvix/Compiler/Core/Extra.hs
  src/Juvix/Compiler/Core/Extra/Base.hs
  src/Juvix/Compiler/Core/Extra/Recursors.hs
  src/Juvix/Compiler/Core/Extra/Recursors/Applicative.hs
  src/Juvix/Compiler/Core/Extra/Recursors/Base.hs
  src/Juvix/Compiler/Core/Extra/Recursors/Collector.hs
  src/Juvix/Compiler/Core/Extra/Recursors/Monadic.hs
Labels: refactor, core

#1499 Clean up import list in Pipeline
  src/Juvix/Compiler/Internal.hs
  src/Juvix/Compiler/Internal/Data.hs
  src/Juvix/Compiler/Internal/Translation.hs
  src/Juvix/Compiler/Internal/Translation/FromAbstract.hs
  src/Juvix/Compiler/Internal/Translation/FromAbstract/Data.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Data.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Data.hs
  src/Juvix/Compiler/Pipeline.hs
Labels: refactor

#1502 Make `juvix compile` default to native target
  README.org
  app/Commands/Compile.hs
  docs/org/tutorials/nodejs-interop.org
Labels: documentation, CLI
