Repository anoma/juvix, pull requests merged in 2023-08, with the labels that each got.

#2260 Add field projections for records
  app/Commands/Dev/Repl/Options.hs
  app/Commands/Repl.hs
  app/Commands/Repl/Options.hs
  src/Juvix/Compiler/Concrete/Data/Scope.hs
  src/Juvix/Compiler/Concrete/Data/Scope/Base.hs
  src/Juvix/Compiler/Concrete/Extra.hs
  src/Juvix/Compiler/Concrete/Gen.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Core/Translation/FromInternal.hs
  src/Juvix/Compiler/Internal/Data/InfoTable.hs
  src/Juvix/Compiler/Internal/Data/InfoTable/Base.hs
  src/Juvix/Compiler/Internal/Extra.hs
  src/Juvix/Compiler/Internal/Translation.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/ArityChecking/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Checker.hs
  src/Juvix/Compiler/Pipeline/Artifacts.hs
  src/Juvix/Compiler/Pipeline/Repl.hs
  src/Juvix/Data/Effect/Fail.hs
  src/Juvix/Prelude.hs
  src/Juvix/Prelude/Pretty.hs
  src/Juvix/Prelude/Stream.hs
  test/Typecheck/Positive.hs
  tests/positive/Projections.juvix
  tests/positive/Records.juvix
  tests/smoke/Commands/repl.smoke.yaml
Labels: enhancement

#2262 Adt syntax
  src/Juvix/Compiler/Concrete/Data/NameSignature/Builder.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Data/Effect/ExactPrint.hs
  test/Scope/Positive.hs
  test/Typecheck/Positive.hs
  tests/positive/Adt.juvix
Labels: syntax

#2267 Disallow iterators with zero ranges
  src/Juvix/Compiler/Concrete/Extra.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Data/IteratorAttribs.hs
  tests/negative/Iterators2.juvix
  tests/positive/Iterators.juvix
Labels: parsing, refactor, syntax

#2268 Fix benchmark wasmer command
  bench/Variants.hs
Labels: CI, benchmark

#2263 Record updates
  runtime/src/juvix/info.h
  src/Juvix/Compiler/Backend/C/Translation/FromReg.hs
  src/Juvix/Compiler/Concrete/Data/Name.hs
  src/Juvix/Compiler/Concrete/Data/NameSignature/Base.hs
  src/Juvix/Compiler/Concrete/Data/NameSignature/Builder.hs
  src/Juvix/Compiler/Concrete/Data/Scope/Base.hs
  src/Juvix/Compiler/Concrete/Extra.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error/Types.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Extra.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Data/Fixity.hs
  test/Compilation/Positive.hs
  test/Scope/Negative.hs
  test/Typecheck/Positive.hs
  tests/Compilation/positive/out/test060.out
  tests/Compilation/positive/test060.juvix
  tests/negative/NoNamedArguments.juvix
  tests/negative/NotARecord.juvix
  tests/negative/UnexpectedFieldUpdate.juvix
  tests/positive/Records.juvix
  tests/positive/Records2.juvix
Labels: enhancement, syntax

#2271 Record patterns
  src/Juvix/Compiler/Concrete/Data/Scope/Base.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error/Types.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  test/Scope/Negative.hs
  test/Typecheck/Positive.hs
  tests/Compilation/positive/test060.juvix
  tests/negative/RepeatedFieldPattern.juvix
  tests/positive/Internal/AsPattern.juvix
  tests/positive/RecordPattern.juvix
Labels: enhancement, syntax

#2284 Prettyprint aggregate ADT constructor types with parentheses
  src/Juvix/Compiler/Concrete/Print/Base.hs
  tests/positive/Format.juvix
Labels: prettyprinting, fix:bug, juvix-formatter

#2283 Fixes behaviour of default stdlib when internal-build-flag is set
  app/Commands/Init.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/PathResolver.hs
  src/Juvix/Compiler/Pipeline/Package.hs
  src/Juvix/Compiler/Pipeline/Root.hs
  tests/smoke/Commands/compile.smoke.yaml
Labels: fix:bug

#2290 Error on duplicate keys in YAML
  package.yaml
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Data/Yaml.hs
  test/Parsing/Negative.hs
  tests/negative/PragmasDuplicateKeys.juvix
Labels: parsing, syntax, fix:bug

#2275 Update stackage resolver to LTS 21.6
  .devcontainer/Dockerfile
  .github/workflows/linux-static-binary.yaml
  app/Commands/Init.hs
  cabal.project
  cabal.project.freeze
  docker/Dockerfile-ghc-alpine-9.2.5
  docker/Dockerfile-ghc-alpine-9.2.7
  docker/README.md
  package.yaml
  src/Juvix/Compiler/Asm/Data/InfoTableBuilder.hs
  src/Juvix/Compiler/Backend/C/Data/CBuilder.hs
  src/Juvix/Compiler/Builtins/Effect.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Core/Data/InfoTableBuilder.hs
  src/Juvix/Compiler/Core/Transformation/NaiveMatchToCase.hs
  src/Juvix/Compiler/Core/Translation/FromInternal.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/ArityChecking/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Reachability.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Checker.hs
  src/Juvix/Compiler/Pipeline/Artifacts.hs
  src/Juvix/Compiler/Pipeline/Package.hs
  src/Juvix/Compiler/Pipeline/Repl.hs
  src/Juvix/Data/Effect/Files/Pure.hs
  src/Juvix/Data/Error/GenericError.hs
  src/Juvix/Data/Yaml.hs
  src/Juvix/Formatter.hs
  src/Juvix/Prelude/Base.hs
  src/Juvix/Prelude/Path/OrphanInstances.hs
  stack.yaml
Labels: ghc

#2278 Improve iterator and named arguments parsing
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  tests/positive/NamedArguments.juvix
Labels: error-messaging, parsing, fix:bug

#2289 Check for incomparable precedences
  runtime/src/juvix/info.h
  src/Juvix/Compiler/Concrete/Data/InfoTable.hs
  src/Juvix/Compiler/Concrete/Data/InfoTableBuilder.hs
  src/Juvix/Compiler/Concrete/Extra.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error/Types.hs
  src/Juvix/Compiler/Core/Language/Nodes.hs
  src/Juvix/Data/DependencyInfo.hs
  src/Juvix/Data/Fixity.hs
  test/Scope/Negative.hs
  tests/negative/IncomparablePrecedences.juvix
Labels: error-messaging, parsing, syntax

#2295 Allow wildcard arguments in new function definition syntax
  src/Juvix/Compiler/Concrete/Data/NameSignature/Builder.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  test/Typecheck/Positive.hs
  tests/positive/WildcardArguments.juvix
Labels: enhancement, parsing, syntax

#2299 add Rhs to SigArg and InductiveParameters
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
Labels: refactor

#2291 Allow omitting `: Type` in implicit function argument definitions and in type definitions
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error/Types.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  test/Typecheck/Positive.hs
  tests/positive/OmitType.juvix
Labels: enhancement, parsing, syntax

#2300 Fix bug in arity checker with pi types
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/ArityChecking/Checker.hs
  test/Typecheck/Positive.hs
  tests/positive/issue2296/M.juvix
  tests/positive/issue2296/juvix.yaml
Labels: fix:bug, aritychecker

#2303 Minor comment updates
  src/Juvix/Compiler/Core/Language.hs
  src/Juvix/Compiler/Core/Transformation/ComputeTypeInfo.hs
Labels: refactor

#2306 Check that type functions are supported
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Data/Inference.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Error.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Error/Types.hs
  test/Typecheck/Negative.hs
  tests/negative/Internal/UnsupportedTypeFunction.juvix
Labels: error-messaging, fix:bug

#2308 Replace gitrev with githash for obtaining build-time git info
  .github/workflows/linux-static-binary.yaml
  package.yaml
  src/Juvix/Extra/Version.hs
Labels: CI, CLI, dev-tools

#2309 Fix shell variables in linux static build stack install
  .github/workflows/linux-static-binary.yaml
Labels: CI

#2301 Aliasing
  app/Commands/Repl.hs
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped/Source.hs
  src/Juvix/Compiler/Concrete/Data/Highlight.hs
  src/Juvix/Compiler/Concrete/Data/Highlight/RenderEmacs.hs
  src/Juvix/Compiler/Concrete/Data/InfoTableBuilder.hs
  src/Juvix/Compiler/Concrete/Data/NameSpace.hs
  src/Juvix/Compiler/Concrete/Data/Scope.hs
  src/Juvix/Compiler/Concrete/Data/Scope/Base.hs
  src/Juvix/Compiler/Concrete/Data/ScopedName.hs
  src/Juvix/Compiler/Concrete/Extra.hs
  src/Juvix/Compiler/Concrete/Keywords.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error/Types.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Extra.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Data/Keyword/All.hs
  src/Juvix/Data/NameKind.hs
  src/Juvix/Extra/Strings.hs
  test/Scope/Negative.hs
  test/Typecheck/Positive.hs
  tests/negative/AliasCycle.juvix
  tests/positive/Alias.juvix
Labels: scoping, enhancement, syntax

#2307 Remove `open import` syntax
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  tests/positive/FancyPaths/Main.juvix
  tests/smoke/Commands/typecheck.smoke.yaml
Labels: parsing, syntax

#2317 Install wasmer binary from Github releases
  .github/workflows/ci.yml
Labels: CI

#2314 Fix record pattern formatting
  src/Juvix/Compiler/Concrete/Print/Base.hs
Labels: fix:bug, juvix-formatter

#2312 Add pragma face
  src/Juvix/Compiler/Concrete/Data/Highlight.hs
  src/Juvix/Compiler/Concrete/Data/Highlight/Properties.hs
  src/Juvix/Compiler/Concrete/Data/ParsedInfoTableBuilder.hs
  src/Juvix/Compiler/Concrete/Data/ParsedItem.hs
  src/Juvix/Extra/Strings.hs
Labels: highlight

#2321 Add css colors `ju-comment` and `ju-judoc`
  assets/css/source-ayu-light.css
  assets/css/source-nord.css
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped/Source.hs
Labels: html

#2318 Report termination errors after typechecking
  app/App.hs
  app/Commands/Dev/Internal/Arity.hs
  app/Commands/Dev/Internal/Pretty.hs
  app/Commands/Dev/Internal/Reachability.hs
  app/Commands/Dev/Termination/CallGraph.hs
  app/Commands/Dev/Termination/Calls.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/FunctionCall.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Data/FunctionCall.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Data/TerminationState.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Error/Types.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Data/Context.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Data/Inference.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Error/Types.hs
  src/Juvix/Compiler/Pipeline.hs
  src/Juvix/Compiler/Pipeline/Artifacts.hs
  src/Juvix/Compiler/Pipeline/Repl.hs
  test/Arity/Negative.hs
  test/Scope/Negative.hs
  test/Termination/Negative.hs
  test/Termination/Positive.hs
  test/Typecheck/Positive.hs
  tests/negative/Internal/issue2293.juvix
  tests/negative/Termination/Axiom.juvix
  tests/negative/Termination/Data/Bool.juvix
  tests/negative/Termination/Data/QuickSort.juvix
  tests/negative/Termination/Ord.juvix
  tests/smoke/Commands/repl.smoke.yaml
Labels: termination, error-messaging, typechecking

#2328 Add fixity face
  src/Juvix/Compiler/Concrete/Data/Highlight/Properties.hs
  src/Juvix/Compiler/Concrete/Data/Highlight/RenderEmacs.hs
Labels: highlight

#2325 Generate function signatures in the html backend
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
Labels: html

#2327 Generate html documentation for alias and fixity definitions
  assets/css/source-ayu-light.css
  assets/css/source-nord.css
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Data/FixityInfo.hs
Labels: html

#2322 Show all available html themes in the CLI automatically
  app/Commands/Html/Options.hs
  src/Juvix/Compiler/Backend/Html/Data/Options.hs
  tests/smoke/Commands/html.smoke.yaml
Labels: CLI
