Repository anoma/juvix, pull requests merged in 2023-07, with the labels that each got.

#2239 Add syntax for builtin list
  src/Juvix/Compiler/Asm/Translation/FromCore.hs
  src/Juvix/Compiler/Builtins.hs
  src/Juvix/Compiler/Builtins/List.hs
  src/Juvix/Compiler/Concrete/Data/Builtins.hs
  src/Juvix/Compiler/Concrete/Keywords.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Core/Translation/FromInternal.hs
  src/Juvix/Compiler/Core/Translation/Stripped/FromCore.hs
  src/Juvix/Compiler/Internal/Extra.hs
  src/Juvix/Compiler/Internal/Extra/DependencyBuilder.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Data/Keyword/All.hs
  src/Juvix/Extra/Strings.hs
  test/Compilation/Positive.hs
  tests/Compilation/positive/juvix.yaml
  tests/Compilation/positive/out/test059.out
  tests/Compilation/positive/test059.juvix
  tests/smoke/Commands/dev/highlight.smoke.yaml
Labels: syntax

#2244 Update to GEB version 0.3.2
  app/Commands/Dev/Geb/Check.hs
  src/Juvix/Compiler/Backend/Geb/Analysis/TypeChecking/Checker.hs
  src/Juvix/Compiler/Backend/Geb/Analysis/TypeChecking/Error.hs
  src/Juvix/Compiler/Backend/Geb/Evaluator.hs
  src/Juvix/Compiler/Backend/Geb/Extra.hs
  src/Juvix/Compiler/Backend/Geb/Language.hs
  src/Juvix/Compiler/Backend/Geb/Pretty/Base.hs
  src/Juvix/Compiler/Backend/Geb/Pretty/Keywords.hs
  src/Juvix/Compiler/Backend/Geb/Translation/FromCore.hs
  src/Juvix/Compiler/Backend/Geb/Translation/FromSource.hs
  src/Juvix/Data/Keyword/All.hs
  src/Juvix/Extra/Strings.hs
  tests/Geb/positive/Compilation/out/test001.geb
  tests/Geb/positive/Compilation/out/test002.geb
  tests/Geb/positive/Compilation/out/test003.geb
  tests/Geb/positive/Compilation/out/test004.geb
  tests/Geb/positive/Compilation/out/test008.geb
  tests/Geb/positive/Compilation/out/test028.geb
  tests/Geb/positive/Eval/out/app-case-on.out
  tests/Geb/positive/Eval/out/app-lambda.out
  tests/Geb/positive/Eval/out/case-on.out
  tests/Geb/positive/Eval/out/lamb.out
  tests/Geb/positive/Eval/out/left-unit.out
  tests/Geb/positive/Eval/out/test001.geb
  tests/Geb/positive/Eval/out/test002.geb
  tests/Geb/positive/Eval/out/test003.geb
  tests/Geb/positive/Eval/out/test004.geb
  tests/Geb/positive/Eval/out/test008.geb
  tests/Geb/positive/app-app-lambda.geb
  tests/Geb/positive/app-case-on.geb
  tests/Geb/positive/app-fst-pair.geb
  tests/Geb/positive/app-lambda.geb
  tests/Geb/positive/basic-app.geb
  tests/Geb/positive/case-on.geb
  tests/Geb/positive/lamb.geb
  tests/Geb/positive/left-unit.geb
  tests/smoke/Commands/dev/geb.smoke.yaml
Labels: backend:geb, translation:core-to-geb, pipeline:geb

#2240 Parse many consecutive `-` as a comment
  src/Juvix/Parser/Lexer.hs
  tests/positive/Format.juvix
Labels: parsing, fix:bug

#2253 Typcheck imports before statements
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Data/Inference.hs
  test/Typecheck/Positive.hs
  tests/positive/issue2248/Bug.juvix
  tests/positive/issue2248/Main.juvix
  tests/positive/issue2248/juvix.yaml
Labels: fix:bug

#2250 Named arguments
  .hlint.yaml
  src/Juvix/Compiler/Concrete/Data/Builtins.hs
  src/Juvix/Compiler/Concrete/Data/Name.hs
  src/Juvix/Compiler/Concrete/Data/NameSignature.hs
  src/Juvix/Compiler/Concrete/Data/NameSignature/Base.hs
  src/Juvix/Compiler/Concrete/Data/NameSignature/Builder.hs
  src/Juvix/Compiler/Concrete/Data/NameSignature/Error.hs
  src/Juvix/Compiler/Concrete/Data/Scope.hs
  src/Juvix/Compiler/Concrete/Extra.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error/Types.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete/NamedArguments.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete/NamedArguments/Error.hs
  src/Juvix/Data/Ape/Base.hs
  src/Juvix/Data/Effect/ExactPrint.hs
  src/Juvix/Data/Effect/Fail.hs
  src/Juvix/Data/Keyword/All.hs
  src/Juvix/Extra/Strings.hs
  src/Juvix/Prelude/Base.hs
  test/Scope/Negative.hs
  test/Typecheck/Positive.hs
  tests/negative/DuplicateArgument.juvix
  tests/negative/DuplicateInductiveParameterName.juvix
  tests/negative/MissingArgument.juvix
  tests/negative/RepeatedNameSignature.juvix
  tests/negative/UnexpectedArgument.juvix
  tests/negative/UnexpectedArgumentWildcard.juvix
  tests/positive/NamedArguments.juvix
Labels: scoping, syntax

#2255 Rename inductive constructor
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped.hs
  src/Juvix/Compiler/Builtins/Bool.hs
  src/Juvix/Compiler/Builtins/Int.hs
  src/Juvix/Compiler/Builtins/List.hs
  src/Juvix/Compiler/Builtins/Nat.hs
  src/Juvix/Compiler/Concrete/Data/InfoTable.hs
  src/Juvix/Compiler/Concrete/Data/InfoTableBuilder.hs
  src/Juvix/Compiler/Concrete/Data/NameSignature/Builder.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Core/Translation/FromInternal.hs
  src/Juvix/Compiler/Internal/Extra.hs
  src/Juvix/Compiler/Internal/Extra/DependencyBuilder.hs
  src/Juvix/Compiler/Internal/Language.hs
  src/Juvix/Compiler/Internal/Pretty/Base.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/ArityChecking/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Checker.hs
Labels: refactor

#2256 Refactor deriving statements in `Concrete.Language`
  src/Juvix/Compiler/Concrete/Data/IsConcrete.hs
  src/Juvix/Compiler/Concrete/Data/ScopedName.hs
  src/Juvix/Compiler/Concrete/Data/Stage.hs
  src/Juvix/Compiler/Concrete/Extra.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
Labels: refactor

#2254 Add record declaration syntax
  src/Juvix/Compiler/Concrete/Data/NameSignature/Builder.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Data/InfoTable.hs
  src/Juvix/Compiler/Internal/Extra.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Data/Effect/ExactPrint.hs
  src/Juvix/Prelude/Lens.hs
  test/Typecheck/Positive.hs
  tests/positive/Records.juvix
Labels: scoping, syntax

#2257 Separate modules namespace
  app/Commands/Repl.hs
  src/Juvix/Compiler/Concrete/Data/InfoTableBuilder.hs
  src/Juvix/Compiler/Concrete/Data/NameSpace.hs
  src/Juvix/Compiler/Concrete/Data/Scope.hs
  src/Juvix/Compiler/Concrete/Data/ScopedName.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error/Types.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Data/NameId.hs
  src/Juvix/Data/NameKind.hs
  test/Scope/Positive.hs
  tests/positive/Namespaces.juvix
Labels: scoping, syntax

#2261 Minor refactor and script update
  Makefile
  cntlines.sh
  package.yaml
  runtime/src/vampir/stdlib.pir
  src/Juvix/Compiler/Backend/VampIR/Pretty/Base.hs
Labels: refactor, dev-tools
