Repository anoma/juvix, pull requests merged in 2024-07, with the labels that each got.

#2863 Improve performance of formatting a project
  app/App.hs
  app/Commands/Dev/Core/Strip.hs
  app/Commands/Dev/Geb/Repl.hs
  app/Commands/Dev/Scope.hs
  app/Commands/Eval.hs
  app/Commands/Format.hs
  app/Commands/Format/Options.hs
  app/Commands/Html.hs
  app/Commands/Markdown.hs
  app/Commands/Repl.hs
  app/CommonOptions.hs
  app/GlobalOptions.hs
  app/TopCommand/Options.hs
  src/Juvix/Compiler/Backend/Isabelle/Translation/FromTyped.hs
  src/Juvix/Compiler/Concrete/Data/Name.hs
  src/Juvix/Compiler/Concrete/Data/Scope/Base.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Data/Context.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource/Data/Context.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Pipeline.hs
  src/Juvix/Compiler/Pipeline/Driver.hs
  src/Juvix/Compiler/Pipeline/DriverParallel.hs
  src/Juvix/Compiler/Pipeline/EntryPoint.hs
  src/Juvix/Compiler/Pipeline/EntryPoint/IO.hs
  src/Juvix/Compiler/Pipeline/JvoCache.hs
  src/Juvix/Compiler/Pipeline/Loader/PathResolver/Base.hs
  src/Juvix/Compiler/Pipeline/Loader/PathResolver/ImportTree/Base.hs
  src/Juvix/Compiler/Pipeline/Loader/PathResolver/Paths.hs
  src/Juvix/Compiler/Pipeline/ModuleInfoCache.hs
  src/Juvix/Compiler/Pipeline/Package/Loader/EvalEff/IO.hs
  src/Juvix/Compiler/Pipeline/Repl.hs
  src/Juvix/Compiler/Pipeline/Run.hs
  src/Juvix/Compiler/Store/Extra.hs
  src/Juvix/Compiler/Store/Language.hs
  src/Juvix/Compiler/Store/Scoped/Language.hs
  src/Juvix/Data.hs
  src/Juvix/Data/Effect.hs
  src/Juvix/Data/Effect/Forcing.hs
  src/Juvix/Data/ModuleId.hs
  src/Juvix/Data/TopModulePathKey.hs
  src/Juvix/Formatter.hs
  src/Juvix/Prelude/Base/Foundation.hs
  src/Parallel/ParallelTemplate.hs
  test/BackendMarkdown/Negative.hs
  test/BackendMarkdown/Positive.hs
  test/Format.hs
  test/Formatter/Positive.hs
  test/Repl/Positive.hs
  test/Scope/Positive.hs
Labels: enhancement, juvix-formatter, performance

#2861 Adapt Anoma builtins to new Anoma Node API
  src/Juvix/Compiler/Builtins/Anoma.hs
  src/Juvix/Compiler/Concrete/Data/Builtins.hs
  src/Juvix/Compiler/Core/Data/InfoTableBuilder.hs
  src/Juvix/Compiler/Core/Evaluator.hs
  src/Juvix/Compiler/Core/Extra/Utils.hs
  src/Juvix/Compiler/Core/Keywords.hs
  src/Juvix/Compiler/Core/Language/Builtins.hs
  src/Juvix/Compiler/Core/Normalizer.hs
  src/Juvix/Compiler/Core/Pretty/Base.hs
  src/Juvix/Compiler/Core/Transformation/ComputeTypeInfo.hs
  src/Juvix/Compiler/Core/Transformation/Optimize/ConstantFolding.hs
  src/Juvix/Compiler/Core/Translation/FromInternal.hs
  src/Juvix/Compiler/Core/Translation/FromSource.hs
  src/Juvix/Compiler/Core/Translation/Stripped/FromCore.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Nockma/Evaluator.hs
  src/Juvix/Compiler/Nockma/Translation/FromTree.hs
  src/Juvix/Compiler/Tree/Keywords.hs
  src/Juvix/Compiler/Tree/Language/Builtins.hs
  src/Juvix/Compiler/Tree/Pretty/Base.hs
  src/Juvix/Compiler/Tree/Transformation/CheckNoAnoma.hs
  src/Juvix/Compiler/Tree/Translation/FromCore.hs
  src/Juvix/Compiler/Tree/Translation/FromSource.hs
  src/Juvix/Data/Keyword/All.hs
  src/Juvix/Extra/Strings.hs
  test/Core/Eval/Base.hs
  test/Tree/Transformation/CheckNoAnoma.hs
  tests/Anoma/Compilation/positive/test078.juvix
  tests/Core/positive/out/test062.out
  tests/Core/positive/test062.jvc
  tests/Tree/negative/test014.jvt
Labels: enhancement, backend:nockma, anoma

#2870 Release 0.6.3
  CHANGELOG.md
  package.yaml
  tests/smoke/Commands/version-help-doctor.smoke.yaml
Labels: release

#2852 Add front-end support for case expressions boolean side conditions
  src/Juvix/Compiler/Backend/Rust/Pretty/Keywords.hs
  src/Juvix/Compiler/Backend/VampIR/Pretty/Keywords.hs
  src/Juvix/Compiler/Concrete/Data/IfBranchKind.hs
  src/Juvix/Compiler/Concrete/Keywords.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Core/Pretty/Base.hs
  src/Juvix/Compiler/Core/Translation/FromInternal.hs
  src/Juvix/Compiler/Internal/Extra/Base.hs
  src/Juvix/Compiler/Internal/Extra/Clonable.hs
  src/Juvix/Compiler/Internal/Extra/DependencyBuilder.hs
  src/Juvix/Compiler/Internal/Extra/HasLetDefs.hs
  src/Juvix/Compiler/Internal/Language.hs
  src/Juvix/Compiler/Internal/Pretty/Base.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Positivity/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/CheckerNew.hs
  src/Juvix/Data/CodeAnn.hs
  src/Juvix/Prelude/Base/Foundation.hs
  tests/positive/Format.juvix
Labels: enhancement, syntax

#2874 Reduce Internal boilerplate
  package.yaml
  src/Juvix/Compiler/Concrete/Data/Highlight/Properties.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Internal/Data/InfoTable.hs
  src/Juvix/Compiler/Internal/Extra.hs
  src/Juvix/Compiler/Internal/Extra/Base.hs
  src/Juvix/Compiler/Internal/Extra/Clonable.hs
  src/Juvix/Compiler/Internal/Extra/DependencyBuilder.hs
  src/Juvix/Compiler/Internal/Extra/HasLetDefs.hs
  src/Juvix/Compiler/Internal/Language.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/CheckerNew.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/CheckerNew/Arity.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Data/Inference.hs
  src/Juvix/Compiler/Pipeline/Lockfile.hs
  src/Juvix/Compiler/Pipeline/Package/Base.hs
  src/Juvix/Compiler/Pipeline/Package/Dependency.hs
  src/Juvix/Prelude/Base/Foundation.hs
Labels: refactor

#2881 Print pipe for else branch in multi if expression
  src/Juvix/Compiler/Concrete/Print/Base.hs
  tests/positive/Format.juvix
Labels: fix:bug

#2880 Add `ExceptT`, `MonadError`, `MonadTrans` as a test
  tests/Compilation/positive/test072/ExceptT.juvix
  tests/Compilation/positive/test072/Functor.juvix
  tests/Compilation/positive/test072/Monad.juvix
  tests/Compilation/positive/test072/MonadError.juvix
  tests/Compilation/positive/test072/MonadTrans.juvix
  tests/Compilation/positive/test072/ReaderT.juvix
Labels: test-suite

#2883 Make `juvix format` line width 100 with ribbon width 100
  examples/demo/Demo.juvix
  examples/midsquare/MidSquareHash.juvix
  examples/midsquare/MidSquareHashUnrolled.juvix
  examples/milestone/Bank/Bank.juvix
  examples/milestone/Collatz/Collatz.juvix
  examples/milestone/Fibonacci/Fibonacci.juvix
  examples/milestone/Hanoi/Hanoi.juvix
  examples/milestone/PascalsTriangle/PascalsTriangle.juvix
  examples/milestone/TicTacToe/CLI/TicTacToe.juvix
  examples/milestone/TicTacToe/Logic/Board.juvix
  examples/milestone/TicTacToe/Logic/Extra.juvix
  examples/milestone/TicTacToe/Logic/Game.juvix
  examples/milestone/TicTacToe/Logic/GameState.juvix
  src/Juvix/Prelude/Pretty.hs
  tests/positive/Ape.juvix
  tests/positive/Format.juvix
  tests/positive/Iterators.juvix
  tests/positive/Judoc.juvix
  tests/positive/StdlibList/Data/List.juvix
  tests/positive/Syntax.juvix
  tests/positive/package/Package.juvix
  tests/smoke/Commands/dev/highlight.smoke.yaml
Labels: enhancement, juvix-formatter

#2889 `juvix typecheck` with no file argument typechecks all project
  app/Commands/Base.hs
  app/Commands/Dev/Highlight.hs
  app/Commands/Format.hs
  app/Commands/Repl.hs
  app/Commands/Typecheck.hs
  src/Juvix/Compiler/Pipeline/Driver.hs
  src/Juvix/Prelude/Base/Foundation.hs
Labels: enhancement, CLI

#2887 Add precondition to run tests
  test/Base.hs
  test/Casm.hs
  test/Casm/Compilation.hs
  test/Casm/Compilation/Base.hs
  test/Casm/Compilation/Positive.hs
  test/Casm/Reg.hs
  test/Casm/Reg/Base.hs
  test/Casm/Reg/Cairo.hs
  test/Casm/Run.hs
  test/Casm/Run/Base.hs
  test/Casm/Run/Positive.hs
  test/Main.hs
  test/Rust.hs
  test/Rust/Compilation.hs
  test/Rust/Compilation/Base.hs
  test/Rust/RiscZero.hs
  test/Rust/RiscZero/Base.hs
  test/VampIR.hs
  test/VampIR/Core/Base.hs
Labels: test-suite

#2890 Puns for named application
  include/package/PackageDescription/V1.juvix
  include/package/PackageDescription/V2.juvix
  src/Juvix/Compiler/Concrete/Data/Name.hs
  src/Juvix/Compiler/Concrete/Language/Base.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  test/Scope/Positive.hs
  tests/positive/Puns.juvix
Labels: enhancement, syntax

#2900 Use ormolu from stackage in the CI
  .github/workflows/ci.yml
  Makefile
  justfile
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
Labels: CI

#2910 Release 0.6.4
  CHANGELOG.md
  package.yaml
  tests/smoke/Commands/version-help-doctor.smoke.yaml
Labels: release

#2909 Allow record fields to be iterators
  src/Juvix/Compiler/Concrete/Data/NameSignature/Builder.hs
  src/Juvix/Compiler/Concrete/Language/Base.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  test/Scope/Positive.hs
  tests/positive/RecordIterator.juvix
Labels: syntax

#2915 Properly handle confluent imports
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Store/Scoped/Data/SymbolEntry.hs
  src/Juvix/Prelude/Base/Foundation.hs
  src/Juvix/Prelude/Effects/Accum.hs
  src/Juvix/Prelude/Effects/Output.hs
  test/Scope/Positive.hs
  tests/positive/ConfluentScoping/A.juvix
  tests/positive/ConfluentScoping/B.juvix
  tests/positive/ConfluentScoping/Main.juvix
  tests/positive/ConfluentScoping/Package.juvix
Labels: scoping, fix:bug

#2916 Allow instance field declarations
  src/Juvix/Compiler/Concrete/Data/NameSignature/Builder.hs
  src/Juvix/Compiler/Concrete/Extra.hs
  src/Juvix/Compiler/Concrete/Language/Base.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Data/InfoTable.hs
  src/Juvix/Compiler/Internal/Extra.hs
  src/Juvix/Compiler/Internal/Extra/Base.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Positivity/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/CheckerNew.hs
  src/Juvix/Data.hs
  src/Juvix/Data/InstanceHole.hs
  src/Juvix/Data/IsImplicit.hs
  src/Juvix/Data/ProjectionKind.hs
  src/Juvix/Prelude/Base/Foundation.hs
  tests/positive/Internal/InstanceFields.juvix
  tests/positive/Isabelle/isabelle/Program.thy
Labels: enhancement, typechecking, traits

#2928 Fix name signature bug and extend test for instance fields
  src/Juvix/Compiler/Concrete/Data/NameSignature/Builder.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Prelude/Trace.hs
  test/Compilation/Positive.hs
  tests/Compilation/positive/out/test077.out
  tests/Compilation/positive/test077.juvix
  tests/positive/Internal/InstanceFields.juvix
Labels: fix:bug

#2920 Do not show progress log for `juvix html`
  app/Commands/Html.hs
Labels: CLI

#2925 Fix #2924. Use MegaParsec scanner for Markdown files
  src/Juvix/Compiler/Concrete/Translation/ImportScanner/FlatParse.hs
  tests/positive/Markdown/Test.juvix.md
  tests/positive/Markdown/markdown/Test.md
Labels: fix:bug

#2929 Fix scanning of names with `import` prefix
  app/Commands/Dev/ImportTree/ScanFile.hs
  app/Commands/Repl.hs
  src/Juvix/Compiler/Concrete/Translation/ImportScanner.hs
  src/Juvix/Compiler/Concrete/Translation/ImportScanner/FlatParse.hs
  src/Juvix/Compiler/Pipeline/Loader/PathResolver/ImportTree.hs
  src/Juvix/Compiler/Pipeline/Repl.hs
  src/Juvix/Compiler/Pipeline/Run.hs
  test/Scope/Positive.hs
  tests/positive/issue2929/Package.juvix
  tests/positive/issue2929/important.juvix
  tests/positive/issue2929/main.juvix
Labels: parsing, fix:bug

#2930 Fix html rendering of fixities
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped.hs
Labels: html, fix:bug
