Repository anoma/juvix, pull requests merged in 2024-02, with the labels that each got.

#2601 JuvixTree negative evaluation tests
  src/Juvix/Compiler/Tree/Evaluator.hs
  test/Tree/Eval.hs
  test/Tree/Eval/Base.hs
  test/Tree/Eval/Negative.hs
  tests/Tree/negative/test001.jvt
  tests/Tree/negative/test002.jvt
  tests/Tree/negative/test003.jvt
  tests/Tree/negative/test004.jvt
  tests/Tree/negative/test005.jvt
  tests/Tree/negative/test006.jvt
  tests/Tree/negative/test007.jvt
  tests/Tree/negative/test008.jvt
Labels: test-suite, juvix-tree

#2608 JuvixTree REPL
  app/Commands/Dev/Tree.hs
  app/Commands/Dev/Tree/Options.hs
  app/Commands/Dev/Tree/Repl.hs
  app/Commands/Dev/Tree/Repl/Options.hs
  app/TreeEvaluator.hs
  src/Juvix/Compiler/Tree/Evaluator.hs
  src/Juvix/Compiler/Tree/Translation/FromSource.hs
  src/Juvix/Compiler/Tree/Translation/FromSource/Base.hs
Labels: enhancement, juvix-tree

#2615 Add a justfile to perform project install, test, clean, format tasks
  justfile
Labels: build

#2618 Replace `egrep` with `grep -E`
  runtime/Makefile.generic
Labels: refactor

#2614 Translation from `Juvix Tree` to `Nockma`
  app/Commands/Dev/Asm/Compile.hs
  app/Commands/Dev/Nockma/Eval.hs
  src/Juvix/Compiler/Nockma/EvalCompiled.hs
  src/Juvix/Compiler/Nockma/Evaluator.hs
  src/Juvix/Compiler/Nockma/Language.hs
  src/Juvix/Compiler/Nockma/Language/Path.hs
  src/Juvix/Compiler/Nockma/Pretty/Base.hs
  src/Juvix/Compiler/Nockma/StdlibFunction.hs
  src/Juvix/Compiler/Nockma/Translation/FromAsm.hs
  src/Juvix/Compiler/Nockma/Translation/FromTree.hs
  src/Juvix/Compiler/Pipeline.hs
  src/Juvix/Compiler/Tree/Data/InfoTable/Base.hs
  src/Juvix/Compiler/Tree/Language.hs
  test/Nockma/Compile.hs
  test/Nockma/Compile/Positive.hs
  test/Nockma/Compile/Tree/Positive.hs
  test/Nockma/Eval/Positive.hs
  tests/Tree/positive/out/test009.nockma.out
  tests/Tree/positive/out/test014.out
  tests/Tree/positive/out/test024.out
  tests/Tree/positive/out/test028.nockma.out
  tests/Tree/positive/out/test031.out
  tests/Tree/positive/out/test035.nockma.out
  tests/Tree/positive/test014.jvt
  tests/Tree/positive/test024.jvt
  tests/Tree/positive/test031.jvt
Labels: backend:nockma

#2616 JuvixTree validation
  app/Commands/Dev/Tree/Read.hs
  src/Juvix/Compiler/Asm/Extra/Memory.hs
  src/Juvix/Compiler/Asm/Extra/Recursors.hs
  src/Juvix/Compiler/Asm/Extra/Type.hs
  src/Juvix/Compiler/Pipeline.hs
  src/Juvix/Compiler/Tree/Data/TransformationId.hs
  src/Juvix/Compiler/Tree/Data/TransformationId/Strings.hs
  src/Juvix/Compiler/Tree/Extra/Type.hs
  src/Juvix/Compiler/Tree/Pipeline.hs
  src/Juvix/Compiler/Tree/Transformation.hs
  src/Juvix/Compiler/Tree/Transformation/Validate.hs
  test/Tree/Eval/Base.hs
  tests/Asm/positive/test032.jva
  tests/Tree/positive/test032.jvt
Labels: juvix-tree

#2624 upgrade to Ghc 9.8.1
  .devcontainer/Dockerfile
  .github/workflows/linux-static-binary.yaml
  app/Commands/Extra/Package.hs
  app/Commands/Repl.hs
  app/HaskelineJB.hs
  app/TopCommand/Options.hs
  cabal.project
  cabal.project.freeze
  package.yaml
  src/Juvix/Compiler/Backend/C/Translation/FromReg.hs
  src/Juvix/Compiler/Backend/Geb/Translation/FromCore.hs
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped.hs
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped/Source.hs
  src/Juvix/Compiler/Backend/Markdown/Translation/FromTyped/Source.hs
  src/Juvix/Compiler/Core/Data/BinderList.hs
  src/Juvix/Compiler/Core/Transformation/MatchToCase.hs
  src/Juvix/Compiler/Core/Transformation/NatToPrimInt.hs
  src/Juvix/Compiler/Core/Transformation/Optimize/CaseCallLifting.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/CheckerNew.hs
  src/Juvix/Compiler/Tree/Translation/FromAsm/Translator.hs
  src/Juvix/Prelude/Base.hs
  src/Juvix/Prelude/DarkArts.hs
  src/Juvix/Prelude/Path.hs
  stack.yaml
Labels: ghc

#2626 Remove BangPattern pragmas
  .github/workflows/ci.yml
  Makefile
  src/Juvix/Compiler/Core/Evaluator.hs
  src/Juvix/Compiler/Tree/Evaluator.hs
  src/Juvix/Prelude/Base.hs
Labels: refactor

#2627 Add `-XBangPatterns` to the justfile
  justfile
Labels: refactor

#2623 Effectful Juvix tree evaluator
  app/Commands/Dev/Tree/Eval.hs
  app/Commands/Dev/Tree/Eval/Options.hs
  app/Commands/Dev/Tree/Read.hs
  app/Commands/Dev/Tree/Repl.hs
  app/TreeEvaluator.hs
  package.yaml
  src/Juvix/Compiler/Tree/Evaluator.hs
  src/Juvix/Compiler/Tree/EvaluatorEff.hs
  src/Juvix/Compiler/Tree/EvaluatorSem.hs
Labels: enhancement

#2629 Use pow2 function from Anoma/Nock stdlib
  src/Juvix/Compiler/Nockma/Evaluator.hs
  src/Juvix/Compiler/Nockma/Evaluator/Options.hs
  src/Juvix/Compiler/Nockma/Language.hs
  src/Juvix/Compiler/Nockma/Stdlib.hs
  src/Juvix/Compiler/Nockma/StdlibFunction.hs
  src/Juvix/Compiler/Nockma/StdlibFunction/Base.hs
  src/Juvix/Compiler/Nockma/Translation/FromTree.hs
  test/Nockma/Eval/Positive.hs
Labels: backend:nockma

#2631 Parse nockma `atomVoid`
  src/Juvix/Compiler/Nockma/Translation/FromSource/Base.hs
Labels: parsing, backend:nockma

#2630 Add nockma as a valid target for the tree compile command
  app/Commands/Dev/Tree/Compile/Options.hs
Labels: CLI

#2628 Add jvt files to `extra-source-files`
  package.yaml
Labels: build, repo-maintenance

#2632 Fix bugs in the Nockma prettyprinter and parser
  package.yaml
  src/Juvix/Compiler/Nockma/Evaluator.hs
  src/Juvix/Compiler/Nockma/Language.hs
  src/Juvix/Compiler/Nockma/Pretty/Base.hs
  src/Juvix/Compiler/Nockma/Translation/FromSource/Base.hs
  test/Nockma/Compile/Tree/Positive.hs
  test/Nockma/Eval/Positive.hs
  test/Nockma/Parse/Positive.hs
  tests/nockma/positive/Compiled.pnock
Labels: refactor, fix:bug, backend:nockma

#2634 Fix linux static binary build workflow
  .github/workflows/linux-static-binary.yaml
Labels: build, repo-maintenance

#2642 Style improvements
  app/Commands/Dev/Asm/Compile.hs
  app/Commands/Dev/Core/Compile/Base.hs
  app/Commands/Dev/Tree/Compile/Base.hs
  src/Juvix/Compiler/Reg/Extra.hs
  src/Juvix/Compiler/Reg/Pretty.hs
  src/Juvix/Compiler/Reg/Pretty/Base.hs
  src/Juvix/Compiler/Tree/Translation/FromSource/Base.hs
Labels: refactor

#2625 Effectful `Output`
  src/Juvix/Compiler/Tree/EvaluatorEff.hs
  src/Juvix/Prelude/Effects.hs
  src/Juvix/Prelude/Effects/Accum.hs
  src/Juvix/Prelude/Effects/Base.hs
  src/Juvix/Prelude/Effects/Output.hs
Labels: refactor

#2637 Remove redundant `embed @IO`
  app/Commands/Compile.hs
  app/Commands/Dev/Core/Compile/Base.hs
  app/Commands/Dev/Tree/Compile/Base.hs
Labels: refactor

#2644 Remove redundant `Embed` effect in the scoper
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
Labels: refactor

#2640 Effect benchmarks
  bench/Main.hs
  bench2/Benchmark/Effect.hs
  bench2/Benchmark/Effect/EmbedIO.hs
  bench2/Benchmark/Effect/Output.hs
  bench2/Benchmark/Effect/Reader.hs
  bench2/Benchmark/Effect/ReaderH.hs
  bench2/Benchmark/Effect/State.hs
  bench2/Main.hs
  package.yaml
  src/Juvix/Prelude/Effects.hs
  src/Juvix/Prelude/Effects/Accum.hs
  src/Juvix/Prelude/Effects/Output.hs
Labels: benchmark

#2635 JuvixReg interpreter
  app/Commands/Dev/Reg.hs
  app/Commands/Dev/Reg/Options.hs
  app/Commands/Dev/Reg/Run.hs
  app/Commands/Dev/Reg/Run/Options.hs
  app/RegInterpreter.hs
  src/Juvix/Compiler/Reg/Error.hs
  src/Juvix/Compiler/Reg/Interpreter.hs
  src/Juvix/Compiler/Reg/Interpreter/Base.hs
  src/Juvix/Compiler/Reg/Interpreter/Error.hs
  src/Juvix/Compiler/Reg/Pretty/Base.hs
  test/Reg.hs
  test/Reg/Run.hs
  test/Reg/Run/Base.hs
  test/Reg/Run/Positive.hs
Labels: juvix-reg

#2655 Transitively register local modules in ScoperState
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  test/Scope/Positive.hs
  tests/positive/ImportNestedLocalModule/ImportNestedLocalModule.juvix
  tests/positive/ImportNestedLocalModule/ImportedModule.juvix
  tests/positive/ImportNestedLocalModule/Package.juvix
Labels: scoping, fix:bug

#2657 Correctly resolve the visibility annotations of NameSpaceEntries
  src/Juvix/Compiler/Concrete/Data/NameSpace.hs
  src/Juvix/Compiler/Concrete/Data/Scope/Base.hs
  src/Juvix/Compiler/Concrete/Data/VisibilityAnn.hs
  test/Scope/Positive.hs
  tests/positive/VisibilityPrecendence/NestedLocalModuleViaExport.juvix
  tests/positive/VisibilityPrecendence/Package.juvix
  tests/positive/VisibilityPrecendence/VisibilityPrecedence.juvix
Labels: fix:bug

#2641 JuvixReg recursors
  app/Commands/Dev/Reg/Read.hs
  app/Commands/Dev/Reg/Read/Options.hs
  app/CommonOptions.hs
  src/Juvix/Compiler/Backend/C/Translation/FromReg.hs
  src/Juvix/Compiler/Backend/C/Translation/FromReg/Base.hs
  src/Juvix/Compiler/Reg/Data/TransformationId.hs
  src/Juvix/Compiler/Reg/Data/TransformationId/Parser.hs
  src/Juvix/Compiler/Reg/Data/TransformationId/Strings.hs
  src/Juvix/Compiler/Reg/Extra/Info.hs
  src/Juvix/Compiler/Reg/Extra/Recursors.hs
  src/Juvix/Compiler/Reg/Interpreter.hs
  src/Juvix/Compiler/Reg/Transformation.hs
  src/Juvix/Compiler/Reg/Transformation/Base.hs
  src/Juvix/Compiler/Reg/Transformation/Identity.hs
  src/Juvix/Compiler/Tree/Transformation.hs
  src/Juvix/Compiler/Tree/Transformation/Apply.hs
  src/Juvix/Compiler/Tree/Transformation/Base.hs
  src/Juvix/Compiler/Tree/Transformation/Generic/Base.hs
  src/Juvix/Compiler/Tree/Transformation/Identity.hs
  src/Juvix/Compiler/Tree/Transformation/TempHeight.hs
  src/Juvix/Compiler/Tree/Transformation/Validate.hs
  test/Reg.hs
  test/Reg/Run/Base.hs
  test/Reg/Run/Positive.hs
  test/Reg/Transformation.hs
  test/Reg/Transformation/Base.hs
  test/Reg/Transformation/Identity.hs
Labels: juvix-reg

#2649 Refactor `readFile` and some parsers to use `Path` instead of `FilePath`
  app/Commands/Dev/Asm/Compile.hs
  app/Commands/Dev/Asm/Run.hs
  app/Commands/Dev/Asm/Validate.hs
  app/Commands/Dev/Casm/Read.hs
  app/Commands/Dev/Casm/Run.hs
  app/Commands/Dev/Core/Asm.hs
  app/Commands/Dev/Core/Compile.hs
  app/Commands/Dev/Core/Eval.hs
  app/Commands/Dev/Core/Normalize.hs
  app/Commands/Dev/Core/Read.hs
  app/Commands/Dev/Core/Repl.hs
  app/Commands/Dev/Core/Strip.hs
  app/Commands/Dev/Geb/Check.hs
  app/Commands/Dev/Geb/Eval.hs
  app/Commands/Dev/Geb/Infer.hs
  app/Commands/Dev/Geb/Read.hs
  app/Commands/Dev/Geb/Repl.hs
  app/Commands/Dev/Nockma/Eval.hs
  app/Commands/Dev/Nockma/Format.hs
  app/Commands/Dev/Nockma/Repl.hs
  app/Commands/Dev/Reg/Read.hs
  app/Commands/Dev/Reg/Run.hs
  app/Commands/Dev/Tree/Compile.hs
  app/Commands/Dev/Tree/Eval.hs
  app/Commands/Dev/Tree/FromAsm.hs
  app/Commands/Dev/Tree/Read.hs
  app/Commands/Dev/Tree/Repl.hs
  bench/Main.hs
  src/Juvix/Compiler/Asm/Translation/FromSource.hs
  src/Juvix/Compiler/Casm/Translation/FromSource.hs
  src/Juvix/Compiler/Nockma/Translation/FromSource/Base.hs
  src/Juvix/Compiler/Reg/Translation/FromSource.hs
  src/Juvix/Compiler/Tree/Translation/FromSource.hs
  src/Juvix/Compiler/Tree/Translation/FromSource/Base.hs
  src/Juvix/Data/Effect/Files/IO.hs
  src/Juvix/Prelude/Base.hs
  test/Asm/Compile/Base.hs
  test/Asm/Run/Base.hs
  test/Asm/Validate/Base.hs
  test/BackendGeb/Eval/Base.hs
  test/BackendGeb/FromCore/Base.hs
  test/BackendMarkdown/Positive.hs
  test/Casm/Run/Base.hs
  test/Core/Asm/Base.hs
  test/Core/Compile/Base.hs
  test/Core/Eval/Base.hs
  test/Core/Print/Base.hs
  test/Format.hs
  test/Internal/Eval/Base.hs
  test/Reg/Parse/Base.hs
  test/Reg/Run/Base.hs
  test/Runtime/Base.hs
  test/Tree/Asm/Base.hs
  test/Tree/Eval/Base.hs
  test/VampIR/Core/Base.hs
Labels: refactor

#2661 Move noFile to common code
  src/Juvix/Compiler/Asm/Translation/FromSource.hs
  src/Juvix/Compiler/Casm/Translation/FromSource.hs
  src/Juvix/Compiler/Nockma/Translation/FromSource/Base.hs
  src/Juvix/Compiler/Reg/Translation/FromSource.hs
  src/Juvix/Compiler/Tree/Translation/FromSource.hs
  src/Juvix/Extra/Paths.hs
Labels: refactor

#2646 Transform JuvixReg into SSA form
  src/Juvix/Compiler/Asm/Extra/Recursors.hs
  src/Juvix/Compiler/Asm/Transformation/StackUsage.hs
  src/Juvix/Compiler/Asm/Transformation/Validate.hs
  src/Juvix/Compiler/Reg/Data/IndexMap.hs
  src/Juvix/Compiler/Reg/Data/TransformationId.hs
  src/Juvix/Compiler/Reg/Data/TransformationId/Strings.hs
  src/Juvix/Compiler/Reg/Extra.hs
  src/Juvix/Compiler/Reg/Extra/Base.hs
  src/Juvix/Compiler/Reg/Extra/Recursors.hs
  src/Juvix/Compiler/Reg/Language.hs
  src/Juvix/Compiler/Reg/Language/Base.hs
  src/Juvix/Compiler/Reg/Pretty/Base.hs
  src/Juvix/Compiler/Reg/Transformation.hs
  src/Juvix/Compiler/Reg/Transformation/SSA.hs
  src/Juvix/Compiler/Reg/Translation/FromAsm.hs
  src/Juvix/Compiler/Reg/Translation/FromSource.hs
  test/Reg/Transformation.hs
  test/Reg/Transformation/SSA.hs
  tests/Reg/positive/test008.jvr
  tests/Reg/positive/test010.jvr
  tests/Reg/positive/test031.jvr
Labels: juvix-reg, cairo

#2647 JuvixReg cleanup transformation
  src/Juvix/Compiler/Pipeline.hs
  src/Juvix/Compiler/Reg/Data/TransformationId.hs
  src/Juvix/Compiler/Reg/Data/TransformationId/Strings.hs
  src/Juvix/Compiler/Reg/Pipeline.hs
  src/Juvix/Compiler/Reg/Transformation.hs
  src/Juvix/Compiler/Reg/Transformation/Cleanup.hs
Labels: juvix-reg, optimization

#2662 Create separate `polysemy` and `effectful` based prelude
  src/Juvix/Prelude/Base.hs
  src/Juvix/Prelude/Base/Foundation.hs
  src/Juvix/Prelude/Base/Polysemy.hs
  src/Juvix/Prelude/BaseEffectful.hs
  src/Juvix/Prelude/Effects/Accum.hs
  src/Juvix/Prelude/Effects/Base.hs
Labels: refactor

#2650 JuvixReg transformation: initialize variables assigned in other branches
  src/Juvix/Compiler/Reg/Data/TransformationId.hs
  src/Juvix/Compiler/Reg/Data/TransformationId/Strings.hs
  src/Juvix/Compiler/Reg/Extra/Recursors.hs
  src/Juvix/Compiler/Reg/Transformation.hs
  src/Juvix/Compiler/Reg/Transformation/InitBranchVars.hs
  test/Reg/Transformation.hs
  test/Reg/Transformation/InitBranchVars.hs
Labels: juvix-reg, cairo

#2666 Fix caseCmd for RepConstr
  src/Juvix/Compiler/Nockma/Translation/FromTree.hs
  test/Anoma/Compilation/Positive.hs
Labels: fix:bug, backend:nockma

#2669 Use the target of aliases when resolving name signatures and iterators
  src/Juvix/Compiler/Concrete/Data/InfoTableBuilder.hs
  src/Juvix/Compiler/Concrete/Extra.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete/NamedArguments.hs
  test/Typecheck/Positive.hs
  tests/positive/AliasRecordConstructor.juvix
Labels: fix:bug

#2653 Generalize backend builtin primitive operations
  src/Juvix/Compiler/Asm/Extra/Base.hs
  src/Juvix/Compiler/Asm/Extra/Recursors.hs
  src/Juvix/Compiler/Asm/Interpreter.hs
  src/Juvix/Compiler/Asm/Language.hs
  src/Juvix/Compiler/Asm/Pretty/Base.hs
  src/Juvix/Compiler/Asm/Transformation/Prealloc.hs
  src/Juvix/Compiler/Asm/Translation/FromSource.hs
  src/Juvix/Compiler/Asm/Translation/FromTree.hs
  src/Juvix/Compiler/Backend/C/Translation/FromReg.hs
  src/Juvix/Compiler/Nockma/Translation/FromTree.hs
  src/Juvix/Compiler/Reg/Extra/Base.hs
  src/Juvix/Compiler/Reg/Extra/Info.hs
  src/Juvix/Compiler/Reg/Interpreter.hs
  src/Juvix/Compiler/Reg/Language.hs
  src/Juvix/Compiler/Reg/Language/Base.hs
  src/Juvix/Compiler/Reg/Pretty/Base.hs
  src/Juvix/Compiler/Reg/Translation/FromAsm.hs
  src/Juvix/Compiler/Reg/Translation/FromSource.hs
  src/Juvix/Compiler/Tree/Evaluator.hs
  src/Juvix/Compiler/Tree/Evaluator/Builtins.hs
  src/Juvix/Compiler/Tree/EvaluatorEff.hs
  src/Juvix/Compiler/Tree/EvaluatorSem.hs
  src/Juvix/Compiler/Tree/Language.hs
  src/Juvix/Compiler/Tree/Language/Builtins.hs
  src/Juvix/Compiler/Tree/Pretty/Base.hs
  src/Juvix/Compiler/Tree/Transformation/Validate.hs
  src/Juvix/Compiler/Tree/Translation/FromAsm.hs
  src/Juvix/Compiler/Tree/Translation/FromCore.hs
  src/Juvix/Compiler/Tree/Translation/FromSource.hs
Labels: refactor

#2639 Update REPL artifacts with builtins from stored modules
  app/Commands/Repl.hs
  app/Evaluator.hs
  src/Juvix/Compiler/Core/Evaluator.hs
  src/Juvix/Compiler/Core/Extra/Value.hs
  src/Juvix/Compiler/Core/Language/Value.hs
  src/Juvix/Compiler/Core/Pretty/Base.hs
  src/Juvix/Compiler/Core/Transformation/MatchToCase.hs
  src/Juvix/Compiler/Pipeline/Artifacts.hs
  src/Juvix/Compiler/Pipeline/Repl.hs
  src/Juvix/Compiler/Store/Extra.hs
  src/Juvix/Data/Error/GenericError.hs
  test/Main.hs
  test/Repl.hs
  test/Repl/Assertions.hs
  test/Repl/Positive.hs
  test/Repl/Value.hs
  tests/smoke/Commands/repl.smoke.yaml
Labels: fix:bug, repl

#2673 Remove `finite-field` dependency
  package.yaml
  src/Juvix/Data/FiniteField/Base.hs
  src/Juvix/Data/FiniteField/PrimeField.hs
  stack.yaml
Labels: refactor
