Repository anoma/juvix, pull requests merged in 2024-03, with the labels that each got.

#2676 Release v0.6.0
  CHANGELOG.md
  bench/hyperfine/Makefile
  package.yaml
  tests/smoke/Commands/version-help-doctor.smoke.yaml
Labels: release

#2681 Add flags for the markdown and html backend: ` --strip-prefix` and `--ext`.
  app/Commands/Html.hs
  app/Commands/Html/Options.hs
  app/Commands/Markdown.hs
  app/Commands/Markdown/Options.hs
  src/Juvix/Compiler/Backend/Html/Data/Options.hs
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped.hs
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped/Source.hs
  src/Juvix/Compiler/Backend/Markdown/Translation/FromTyped/Source.hs
  test/BackendMarkdown/Positive.hs
  tests/smoke/Commands/html.smoke.yaml
Labels: backend:markdown, backend:html

#2694 Promote use of `MonadIO` to minimize `embed` occurrences
  app/App.hs
  app/Commands/Dev/Casm/Run.hs
  app/Commands/Dev/Core/Read.hs
  app/Commands/Dev/Core/Repl.hs
  app/Commands/Dev/Geb/Repl.hs
  app/Commands/Extra/Compile.hs
  app/Commands/Format.hs
  app/Commands/Init.hs
  app/TopCommand.hs
  src/Juvix/Compiler/Asm/Interpreter/Runtime.hs
  src/Juvix/Compiler/Casm/Translation/FromSource.hs
  src/Juvix/Compiler/Core/Scoper.hs
  src/Juvix/Compiler/Nockma/Stdlib.hs
  src/Juvix/Compiler/Nockma/StdlibFunction.hs
  src/Juvix/Compiler/Pipeline/Run.hs
  src/Juvix/Compiler/Reg/Interpreter.hs
  src/Juvix/Compiler/Tree/Evaluator.hs
  src/Juvix/Compiler/Tree/EvaluatorEff.hs
  src/Juvix/Extra/Version.hs
  src/Juvix/Prelude/Base/Foundation.hs
  src/Juvix/Prelude/Prepath.hs
  src/Juvix/Prelude/Pretty.hs
  test/Base.hs
  test/Formatter/Positive.hs
  test/Nockma/Compile/Tree/Positive.hs
  test/Repl/Positive.hs
Labels: refactor

#2695 Rename `Const` constructor in Tree and Reg languages
  src/Juvix/Compiler/Asm/Translation/FromTree.hs
  src/Juvix/Compiler/Backend/C/Translation/FromReg.hs
  src/Juvix/Compiler/Casm/Translation/FromReg.hs
  src/Juvix/Compiler/Core/Language/Base.hs
  src/Juvix/Compiler/Nockma/Translation/FromTree.hs
  src/Juvix/Compiler/Reg/Extra/Base.hs
  src/Juvix/Compiler/Reg/Extra/Info.hs
  src/Juvix/Compiler/Reg/Interpreter.hs
  src/Juvix/Compiler/Reg/Language.hs
  src/Juvix/Compiler/Reg/Pretty/Base.hs
  src/Juvix/Compiler/Reg/Transformation/InitBranchVars.hs
  src/Juvix/Compiler/Reg/Translation/FromAsm.hs
  src/Juvix/Compiler/Reg/Translation/FromSource.hs
  src/Juvix/Compiler/Tree/Evaluator.hs
  src/Juvix/Compiler/Tree/EvaluatorEff.hs
  src/Juvix/Compiler/Tree/EvaluatorSem.hs
  src/Juvix/Compiler/Tree/Extra/Base.hs
  src/Juvix/Compiler/Tree/Language.hs
  src/Juvix/Compiler/Tree/Pretty/Base.hs
  src/Juvix/Compiler/Tree/Transformation/Validate.hs
  src/Juvix/Compiler/Tree/Translation/FromSource.hs
Labels: refactor

#2696 Rename `Dynamic'` to `DynamicTy'`
  src/Juvix/Compiler/Core/Extra/Base.hs
  src/Juvix/Compiler/Core/Language.hs
  src/Juvix/Compiler/Core/Language/Nodes.hs
  src/Juvix/Compiler/Core/Transformation/ComputeTypeInfo.hs
  src/Juvix/Compiler/Core/Translation/Stripped/FromCore.hs
  src/Juvix/Compiler/Store/Core/Extra.hs
  src/Juvix/Compiler/Store/Core/Language.hs
Labels: refactor

#2693 Support compilation of Anoma transactions in nockma backend
  app/Commands/Compile.hs
  app/Commands/Dev/Asm/Compile.hs
  app/Commands/Dev/Core/Compile.hs
  app/Commands/Dev/Core/Compile/Base.hs
  app/Commands/Dev/Nockma.hs
  app/Commands/Dev/Nockma/Eval.hs
  app/Commands/Dev/Nockma/Eval/Options.hs
  app/Commands/Dev/Nockma/Options.hs
  app/Commands/Dev/Nockma/Run.hs
  app/Commands/Dev/Nockma/Run/Options.hs
  app/Commands/Dev/Reg/Compile.hs
  app/Commands/Dev/Tree/Compile.hs
  app/Commands/Dev/Tree/Compile/Base.hs
  app/Commands/Dev/Tree/Compile/Options.hs
  app/Commands/Extra/Compile.hs
  app/Commands/Extra/Compile/Options.hs
  src/Juvix/Compiler/Backend.hs
  src/Juvix/Compiler/Nockma/Anoma.hs
  src/Juvix/Compiler/Nockma/EvalCompiled.hs
  src/Juvix/Compiler/Nockma/Evaluator.hs
  src/Juvix/Compiler/Nockma/Evaluator/Crumbs.hs
  src/Juvix/Compiler/Nockma/Evaluator/Error.hs
  src/Juvix/Compiler/Nockma/Language.hs
  src/Juvix/Compiler/Nockma/Pretty.hs
  src/Juvix/Compiler/Nockma/Pretty/Base.hs
  src/Juvix/Compiler/Nockma/Pretty/Options.hs
  src/Juvix/Compiler/Nockma/Translation/FromSource/Base.hs
  src/Juvix/Compiler/Nockma/Translation/FromTree.hs
  src/Juvix/Compiler/Pipeline.hs
  src/Juvix/Extra/Strings.hs
  test/Anoma/Compilation.hs
  test/Anoma/Compilation/Negative.hs
  test/Anoma/Compilation/Positive.hs
  test/Nockma/Base.hs
  test/Nockma/Compile/Tree/Positive.hs
  test/Nockma/Eval/Positive.hs
  tests/Anoma/Compilation/negative/String.juvix
Labels: backend:nockma, anoma

#2699 Release 0.6.1
  CHANGELOG.md
  package.yaml
  tests/smoke/Commands/version-help-doctor.smoke.yaml
Labels: release

#2701 Move the Nockma standard library to a separate file
  package.yaml
  runtime/src/nockma/stdlib.nockma
  src/Juvix/Compiler/Nockma/Stdlib.hs
Labels: refactor, backend:nockma, anoma

#2706 Fix casm test failures due to concurrent calls to setCurrentDir
  test/Casm/Run/Base.hs
  test/Runtime/Base.hs
Labels: test-suite

#2707 Cache cairo-vm-cli in the CI build
  .github/workflows/ci.yml
Labels: CI, cairo
