Repository anoma/juvix, pull requests merged in 2024-06, with the labels that each got.

#2795 Release 0.6.2
  CHANGELOG.md
  package.yaml
  tests/smoke/Commands/version-help-doctor.smoke.yaml
Labels: release

#2798 Support Anoma stdlib sign-detached API
  src/Juvix/Compiler/Builtins/Anoma.hs
  src/Juvix/Compiler/Concrete/Data/Builtins.hs
  src/Juvix/Compiler/Core/Evaluator.hs
  src/Juvix/Compiler/Core/Extra/Utils.hs
  src/Juvix/Compiler/Core/Language/Builtins.hs
  src/Juvix/Compiler/Core/Pretty/Base.hs
  src/Juvix/Compiler/Core/Transformation/ComputeTypeInfo.hs
  src/Juvix/Compiler/Core/Translation/FromInternal.hs
  src/Juvix/Compiler/Core/Translation/Stripped/FromCore.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Nockma/Encoding/ByteString.hs
  src/Juvix/Compiler/Nockma/Evaluator.hs
  src/Juvix/Compiler/Nockma/StdlibFunction.hs
  src/Juvix/Compiler/Nockma/StdlibFunction/Base.hs
  src/Juvix/Compiler/Nockma/Translation/FromTree.hs
  src/Juvix/Compiler/Tree/Keywords.hs
  src/Juvix/Compiler/Tree/Language/Builtins.hs
  src/Juvix/Compiler/Tree/Pretty/Base.hs
  src/Juvix/Compiler/Tree/Transformation/CheckNoAnoma.hs
  src/Juvix/Compiler/Tree/Translation/FromCore.hs
  src/Juvix/Compiler/Tree/Translation/FromSource.hs
  src/Juvix/Data/Keyword/All.hs
  src/Juvix/Extra/Strings.hs
  test/Tree/Transformation/CheckNoAnoma.hs
  tests/Anoma/Compilation/positive/test077.juvix
  tests/Tree/negative/test015.jvt
Labels: backend:nockma, anoma

#2802 Fix generation of wildcards in RecordPattern
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  tests/positive/RecordPattern.juvix
Labels: fix:bug

#2752 Juvix to Isabelle/HOL translation
  app/Commands/Isabelle.hs
  app/Commands/Isabelle/Options.hs
  app/TopCommand.hs
  app/TopCommand/Options.hs
  cntlines.sh
  src/Juvix/Compiler/Backend/Isabelle/Data/Result.hs
  src/Juvix/Compiler/Backend/Isabelle/Language.hs
  src/Juvix/Compiler/Backend/Isabelle/Pretty.hs
  src/Juvix/Compiler/Backend/Isabelle/Pretty/Base.hs
  src/Juvix/Compiler/Backend/Isabelle/Pretty/Keywords.hs
  src/Juvix/Compiler/Backend/Isabelle/Pretty/Options.hs
  src/Juvix/Compiler/Backend/Isabelle/Translation/FromTyped.hs
  src/Juvix/Compiler/Internal/Extra/Base.hs
  src/Juvix/Compiler/Internal/Language.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/CheckerNew.hs
  src/Juvix/Compiler/Pipeline.hs
  src/Juvix/Compiler/Pipeline/EntryPoint.hs
  src/Juvix/Data/FileExt.hs
  src/Juvix/Prelude/Prepath.hs
Labels: enhancement, isabelle

#2792 RISC0 Rust backend
  .github/workflows/ci.yml
  app/Commands/Compile.hs
  app/Commands/Compile/CommonOptions.hs
  app/Commands/Compile/Options.hs
  app/Commands/Compile/RiscZeroRust.hs
  app/Commands/Compile/RiscZeroRust/Options.hs
  app/Commands/Dev/Asm/Compile.hs
  app/Commands/Dev/Casm/Compile.hs
  app/Commands/Dev/Core/Compile.hs
  app/Commands/Dev/Core/Compile/Base.hs
  app/Commands/Dev/Core/Compile/Options.hs
  app/Commands/Dev/DevCompile/NativeRust.hs
  app/Commands/Dev/Reg/Compile.hs
  app/Commands/Dev/Tree/CompileOld/Base.hs
  app/Commands/Extra/Compile.hs
  app/Commands/Extra/Compile/Options.hs
  app/Commands/Extra/NewCompile.hs
  package.yaml
  runtime/Makefile
  runtime/rust/juvix/.gitignore
  runtime/rust/juvix/Cargo.toml
  runtime/rust/juvix/src/apply.rs
  runtime/rust/juvix/src/closure.rs
  runtime/rust/juvix/src/constr.rs
  runtime/rust/juvix/src/defs.rs
  runtime/rust/juvix/src/equality.rs
  runtime/rust/juvix/src/integer.rs
  runtime/rust/juvix/src/lib.rs
  runtime/rust/juvix/src/memory.rs
  runtime/rust/risc0/.gitignore
  runtime/rust/risc0/Cargo.toml
  runtime/rust/risc0/host/Cargo.toml
  runtime/rust/risc0/host/src/main.rs
  runtime/rust/risc0/methods/Cargo.toml
  runtime/rust/risc0/methods/build.rs
  runtime/rust/risc0/methods/guest/Cargo.toml
  runtime/rust/risc0/methods/guest/src/main.rs
  runtime/rust/risc0/methods/src/lib.rs
  runtime/rust/risc0/rust-toolchain.toml
  src/Juvix/Compiler/Backend/Rust/Data/Backend.hs
  src/Juvix/Compiler/Backend/Rust/Pretty/Base.hs
  src/Juvix/Compiler/Backend/Rust/Pretty/Options.hs
  src/Juvix/Compiler/Backend/Rust/Translation/FromReg.hs
  src/Juvix/Compiler/Internal/Data/InfoTable.hs
  src/Juvix/Compiler/Pipeline.hs
  src/Juvix/Compiler/Pipeline/Options.hs
  src/Juvix/Data/FileExt.hs
  src/Juvix/Prelude/Path.hs
  test/Base.hs
  test/Main.hs
  test/Rust.hs
  test/Rust/Compilation/Base.hs
  test/Rust/RiscZero.hs
  test/Rust/RiscZero/Base.hs
  test/Rust/RiscZero/Positive.hs
  tests/Rust/Compilation/positive/out/test022.out
  tests/Rust/Compilation/positive/test022.juvix
Labels: rust-backend, risc5, risc0-backend

#2817 Add `LeafExpression` to make `leafExpressions` type more explicit
  src/Juvix/Compiler/Internal/Extra/Base.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Data/Inference.hs
Labels: refactor

#2816 Add pedantic option to justfile
  justfile
Labels: dev-tools

#2814 Report proper location for normalized types in the `WrongType` error
  src/Juvix/Compiler/Concrete/Translation/ImportScanner/FlatParse.hs
  src/Juvix/Compiler/Core/Translation/FromInternal.hs
  src/Juvix/Compiler/Internal/Language.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Positivity/Checker.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/CheckerNew.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Data/Inference.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Error/Types.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Traits/Resolver.hs
  src/Juvix/Data.hs
Labels: error-messaging, fix:bug

#2824 Update CHANGELOG for 0.6.2
  CHANGELOG.md
Labels: release

#2847 Add lcomposition fixity to support (>>) in the stdlib
  include/package-base/Juvix/Builtin/V1/Fixity.juvix
Labels: standard-library, language

#2819 Generalize import syntax
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped.hs
  src/Juvix/Compiler/Backend/Markdown/Translation/FromTyped/Source.hs
  src/Juvix/Compiler/Concrete/Data.hs
  src/Juvix/Compiler/Concrete/Data/IsOpenShort.hs
  src/Juvix/Compiler/Concrete/Data/LocalModuleOrigin.hs
  src/Juvix/Compiler/Concrete/Data/PublicAnn.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping/Error/Types.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Pipeline/Package/Loader.hs
  src/Juvix/Compiler/Pipeline/Repl.hs
  src/Juvix/Data/Effect/ExactPrint.hs
  src/Juvix/Prelude/Base/Foundation.hs
  test/Scope/Positive.hs
  tests/positive/DefaultValues.juvix
  tests/positive/Format.juvix
  tests/positive/PublicImports/M.juvix
  tests/positive/PublicImports/Main.juvix
  tests/positive/PublicImports/Package.juvix
Labels: enhancement, syntax, modules

#2566 Add error message for ill-scoped variables
  src/Juvix/Compiler/Core/Translation/FromInternal.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Error.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Error/Types.hs
  src/Juvix/Compiler/Pipeline/Repl.hs
  test/Compilation/Negative.hs
  tests/Compilation/negative/test006.juvix
Labels: error-messaging

#2856 Support Anoma representation of Maybe
  src/Juvix/Compiler/Nockma/Translation/FromTree.hs
  test/Anoma/Compilation/Positive.hs
  tests/Anoma/Compilation/positive/test080.juvix
Labels: enhancement, backend:nockma, anoma
