Repository anoma/juvix, pull requests merged in 2024-04, with the labels that each got.

#2708 Alternative instances for `Eq`, `Hashable` for `StorageKey`
  src/Juvix/Compiler/Nockma/Evaluator/Storage.hs
Labels: enhancement

#2705 Capture scry id in the main function and use it when compiling anomaGet
  src/Juvix/Compiler/Nockma/Evaluator.hs
  src/Juvix/Compiler/Nockma/Evaluator/Error.hs
  src/Juvix/Compiler/Nockma/Evaluator/Storage.hs
  src/Juvix/Compiler/Nockma/Translation/FromTree.hs
  test/Anoma/Compilation/Positive.hs
  test/Nockma/Eval/Positive.hs
Labels: backend:nockma, anoma

#2714 Miscellaneous improvements for Nockma debugging
  app/Commands/Dev/Nockma/Repl.hs
  src/Juvix/Compiler/Nockma/Language.hs
  src/Juvix/Compiler/Nockma/Pretty/Base.hs
  src/Juvix/Compiler/Nockma/Translation/FromTree.hs
  src/Juvix/Extra/Strings.hs
  test/Nockma/Eval/Positive.hs
Labels: backend:nockma

#2715 Double substitute the Nockma functions placeholder in the main function
  src/Juvix/Compiler/Nockma/Translation/FromTree.hs
Labels: backend:nockma

#2717 Fix benchmarks suite `juvix compile` variants
  bench/Main.hs
  bench/Variants.hs
Labels: benchmark

#2711 Use `prettyString` instead of `show . pretty`
  src/Juvix/Prelude/Pretty.hs
  test/Asm/Run/Base.hs
  test/BackendGeb/Eval/Base.hs
  test/BackendGeb/FromCore/Base.hs
  test/Casm/Compilation/Base.hs
  test/Casm/Reg/Base.hs
  test/Casm/Run/Base.hs
  test/Core/Asm/Base.hs
  test/Core/Compile/Base.hs
  test/Core/Eval/Base.hs
  test/Core/Normalize/Base.hs
  test/Core/Print/Base.hs
  test/Core/VampIR/Base.hs
  test/Internal/Eval/Base.hs
  test/Nockma/Parse/Positive.hs
  test/Reg/Parse/Base.hs
  test/Reg/Run/Base.hs
  test/Tree/Asm/Base.hs
  test/Tree/Eval/Base.hs
  test/Tree/Transformation/CheckNoAnoma.hs
  test/VampIR/Core/Base.hs
Labels: refactor

#2728 `--debug` implies `-O0` as the default
  app/Commands/Compile/CommonOptions.hs
Labels: CLI, fix:bug

#2729 Support parallel module compilation in justfile
  justfile
Labels: dev-tools

#2730 Use the justfile for CI builds
  .github/workflows/ci.yml
  justfile
Labels: CI

#2734 Support `extract-module-statements` attribute in juvix code blocks
  src/Juvix/Compiler/Backend/Markdown/Data/MkJuvixBlockOptions.hs
  src/Juvix/Compiler/Backend/Markdown/Data/Types.hs
  src/Juvix/Compiler/Backend/Markdown/Error.hs
  src/Juvix/Compiler/Backend/Markdown/Translation/FromTyped/Source.hs
  src/Juvix/Parser/Error.hs
  src/Juvix/Parser/Error/Base.hs
  test/BackendMarkdown/Negative.hs
  tests/negative/Markdown/InvalidCodeBlockExtraAttribute.juvix.md
  tests/negative/Markdown/InvalidCodeBlockUnknownAttribute.juvix.md
  tests/negative/Markdown/InvalidExtractModuleBlockNoModule.juvix.md
  tests/negative/Markdown/InvalidExtractModuleBlockNotJustModule.juvix.md
  tests/positive/Markdown/Test.juvix.md
  tests/positive/Markdown/markdown/Test.md
Labels: backend:markdown

#2738 remove redundant GitClone constraint
  src/Juvix/Compiler/Pipeline.hs
  src/Juvix/Compiler/Pipeline/Driver.hs
Labels: refactor

#2739 Style refactor
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Pipeline.hs
  src/Juvix/Compiler/Pipeline/Driver.hs
  src/Juvix/Extra/Serialize.hs
Labels: refactor

#2747 Remove support for examples from judoc
  app/Commands/Html.hs
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped.hs
  src/Juvix/Compiler/Concrete/Data/Highlight/PrettyJudoc.hs
  src/Juvix/Compiler/Concrete/Language.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource/Lexer.hs
  src/Juvix/Compiler/Internal/Extra.hs
  src/Juvix/Compiler/Internal/Extra/Base.hs
  src/Juvix/Compiler/Internal/Extra/Clonable.hs
  src/Juvix/Compiler/Internal/Language.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/CheckerNew.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Data/Context.hs
Labels: judoc, backend:html

#2740 Fix benchmark runtime variant
  bench/Variants.hs
Labels: benchmark

#2746 Add integer literals with bases
  src/Juvix/Compiler/Asm/Translation/FromSource.hs
  src/Juvix/Compiler/Backend/Cairo/Extra/Deserialization.hs
  src/Juvix/Compiler/Backend/Cairo/Extra/Serialization.hs
  src/Juvix/Compiler/Backend/Geb/Translation/FromSource/Lexer.hs
  src/Juvix/Compiler/Casm/Translation/FromSource.hs
  src/Juvix/Compiler/Casm/Translation/FromSource/Lexer.hs
  src/Juvix/Compiler/Concrete/Data/Literal.hs
  src/Juvix/Compiler/Concrete/Gen.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource/Lexer.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource/ParserResultBuilder.hs
  src/Juvix/Compiler/Core/Translation/FromSource.hs
  src/Juvix/Compiler/Core/Translation/FromSource/Lexer.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Reg/Translation/FromSource/Lexer.hs
  src/Juvix/Compiler/Tree/Translation/FromSource/Base.hs
  src/Juvix/Compiler/Tree/Translation/FromSource/Lexer/Base.hs
  src/Juvix/Extra/Strings.hs
  src/Juvix/Parser/Lexer.hs
  src/Juvix/Prelude/Base/Foundation.hs
  tests/positive/Format.juvix
Labels: enhancement, syntax

#2741 Fix dev compile options documentation
  app/Commands/Extra/Compile/Options.hs
Labels: documentation, CLI

#2748 Remove unused `resourcet-effectful` dependency
  package.yaml
  stack.yaml
Labels: refactor

#2754 Use aarch64 macOS agent for CI build
  .github/workflows/ci.yml
Labels: CI

#2753 Support sharing ModuleInfoCache between pipeline runs
  src/Juvix/Compiler/Pipeline.hs
  src/Juvix/Compiler/Pipeline/Driver.hs
  src/Juvix/Compiler/Pipeline/ImportParents.hs
  src/Juvix/Compiler/Pipeline/ModuleInfoCache.hs
  src/Juvix/Compiler/Pipeline/Package/Loader/EvalEff/IO.hs
  src/Juvix/Compiler/Pipeline/Repl.hs
  src/Juvix/Compiler/Pipeline/Run.hs
Labels: backend:html

#2756 Fully respect _evalOptionsNoFailure in the Core evaluator
  src/Juvix/Compiler/Core/Evaluator.hs
  tests/Casm/Compilation/positive/test075.juvix
Labels: fix:bug, core, optimization
