Repository anoma/juvix, pull requests merged in 2024-09, with the labels that each got.

#2993 Release 0.6.6
  CHANGELOG.md
  package.yaml
  tests/smoke/Commands/version-help-doctor.smoke.yaml
Labels: release

#2995 Fix locations in Internal hole substitution (only for the case of substituting identifiers)
  src/Juvix/Compiler/Internal/Builtins.hs
  src/Juvix/Compiler/Internal/Data/Name.hs
  src/Juvix/Compiler/Internal/Data/TypedIden.hs
  src/Juvix/Compiler/Internal/Extra.hs
  src/Juvix/Compiler/Internal/Extra/CoercionInfo.hs
  src/Juvix/Compiler/Internal/Extra/InstanceInfo.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/CheckerNew.hs
  src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Traits/Resolver.hs
  src/Juvix/Compiler/Store/Internal/Data/CoercionInfo.hs
  src/Juvix/Compiler/Store/Internal/Data/InstanceInfo.hs
Labels: typechecking, fix:bug, traits

#3003 Remove legacy naive match-to-case compiler
  src/Juvix/Compiler/Core/Data/TransformationId.hs
  src/Juvix/Compiler/Core/Data/TransformationId/Strings.hs
  src/Juvix/Compiler/Core/Transformation.hs
  src/Juvix/Compiler/Core/Transformation/NaiveMatchToCase.hs
  src/Juvix/Compiler/Core/Transformation/NaiveMatchToCase/Data.hs
Labels: refactor, pattern-matching

#3011 Fix location of scoped modulePathName
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  test/Scope/Positive.hs
  tests/positive/issue2737/M.juvix
  tests/positive/issue2737/Package.juvix
  tests/positive/issue2737/main.juvix
Labels: fix:bug, juvix-formatter

#3015 Fix RISC0 compilation on the CI
  .github/workflows/ci.yml
Labels: CI, fix:bug

#3025 Fix RISC0 in the CI
  .github/workflows/ci.yml
Labels: CI, fix:bug

#3024 Fix JuvixTree parsing and pretty printing
  src/Juvix/Compiler/Core/Data/InfoTable.hs
  src/Juvix/Compiler/Core/Data/Module.hs
  src/Juvix/Compiler/Core/Data/TransformationId.hs
  src/Juvix/Compiler/Core/Language/Base.hs
  src/Juvix/Compiler/Core/Language/Builtins.hs
  src/Juvix/Compiler/Core/Transformation/DisambiguateNames.hs
  src/Juvix/Compiler/Core/Translation/Stripped/FromCore.hs
  src/Juvix/Compiler/Tree/Keywords.hs
  src/Juvix/Compiler/Tree/Pretty/Base.hs
  src/Juvix/Compiler/Tree/Pretty/Extra.hs
  src/Juvix/Compiler/Tree/Translation/FromSource.hs
  src/Juvix/Compiler/Tree/Translation/FromSource/Base.hs
  src/Juvix/Data/Keyword/All.hs
  src/Juvix/Extra/Strings.hs
  src/Juvix/Prelude/Base/Foundation.hs
  test/Tree.hs
  test/Tree/Parse.hs
  test/Tree/Parse/Base.hs
  test/Tree/Parse/Positive.hs
Labels: parsing, prettyprinting, juvix-tree

#3026 Remove old named application syntax
  src/Juvix/Compiler/Concrete/Data/Name.hs
  src/Juvix/Compiler/Concrete/Data/NameSignature/Builder.hs
  src/Juvix/Compiler/Concrete/Extra.hs
  src/Juvix/Compiler/Concrete/Gen.hs
  src/Juvix/Compiler/Concrete/Language/Base.hs
  src/Juvix/Compiler/Concrete/Language/IsApeInstances.hs
  src/Juvix/Compiler/Concrete/MigrateNamedApplication.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete.hs
  src/Juvix/Compiler/Internal/Translation/FromConcrete/NamedArguments.hs
  src/Juvix/Compiler/Pipeline/Package/Loader.hs
  src/Juvix/Compiler/Pipeline/Package/Loader/Versions.hs
  tests/smoke/Commands/compile-dependencies-package-juvix.smoke.yaml
  tests/smoke/Commands/compile-dependencies.smoke.yaml
Labels: syntax

#3035 Update cabal.project.freeze for GHC 9.10.1 update
  cabal.project
  cabal.project.freeze
Labels: build

#3038 Precompute debug operations info in linear time
  src/Juvix/Compiler/Core/Extra/Utils.hs
  src/Juvix/Compiler/Core/Info/DebugOpsInfo.hs
  src/Juvix/Compiler/Core/Transformation/Optimize/LetFolding.hs
Labels: core, optimization

#3052 Revert GHC 9.10.1 update
  .github/workflows/ci.yml
  .github/workflows/linux-static-binary.yaml
  cabal.project
  cabal.project.freeze
  package.yaml
  src/Juvix/Data/Effect/Cache.hs
  src/Juvix/Prelude.hs
  stack.yaml
Labels: CI, build, ghc

#3012 Improve parsing error for missing @ in named application
  src/Juvix/Compiler/Backend/Html/Translation/FromTyped.hs
  src/Juvix/Compiler/Concrete/Language/Base.hs
  src/Juvix/Compiler/Concrete/Print/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource.hs
  src/Juvix/Compiler/Concrete/Translation/FromSource/ParserResultBuilder.hs
  src/Juvix/Data/CodeAnn.hs
  src/Juvix/Parser/Error.hs
  test/Parsing/Negative.hs
  tests/negative/NamedApplicationMissingAt.juvix
Labels: error-messaging

#3069 Include the juvix version in the build directory path
  src/Juvix/Compiler/Pipeline/Package/Base.hs
  src/Juvix/Extra/Paths/Base.hs
  tests/positive/Dependencies/.libs/Extra/Package.juvix
  tests/smoke/Commands/compile-dependencies-package-juvix.smoke.yaml
  tests/smoke/Commands/compile-dependencies.smoke.yaml
  tests/smoke/Commands/compile.smoke.yaml
Labels: CLI

#3072 Ignore files that start with a `.`
  src/Juvix/Data/FileExt.hs
  test/Scope/Positive.hs
  tests/positive/issue3068/.hidden.juvix
  tests/positive/issue3068/Package.juvix
  tests/positive/issue3068/main.juvix
  tests/smoke/Commands/typecheck.smoke.yaml
Labels: fix:bug

#3073 Remove unused field from `ScoperState`
  src/Juvix/Compiler/Concrete/Data/Scope/Base.hs
  src/Juvix/Compiler/Concrete/Translation/FromParsed/Analysis/Scoping.hs
Labels: refactor
